import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { notFound } from 'next/navigation';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import CatalogClient from '@/components/CatalogClient';
import JsonLd from '@/components/JsonLd';
import { getCategories, getPublicCatalogPage, getPublicTagBySlug, getSiteSettings } from '@/lib/db';
import { siteUrl } from '@/lib/config';
import { slugifyText } from '@/lib/seo';
type Props={params:Promise<{slug:string}>};
export const dynamic='force-dynamic';
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const [theme,settings]=await Promise.all([getPublicTagBySlug(slug),getSiteSettings()]);if(!theme)return{title:'Tema não encontrado'};const title=`${theme.tag} | ${settings.brand_name}`;const description=`Explore ${theme.count} ${theme.count===1?'peça':'peças'} de papelaria personalizada com o tema ${theme.tag}.`;return{title,description,alternates:siteUrl?{canonical:`${siteUrl}/temas/${slugifyText(theme.tag)}`}:{},openGraph:{title,description,type:'website'}};}
export default async function ThemePage({params}:Props){const {slug}=await params;const [theme,settings,categories]=await Promise.all([getPublicTagBySlug(slug),getSiteSettings(),getCategories()]);if(!theme)return notFound();const catalog=await getPublicCatalogPage({tag:theme.tag,page:1,pageSize:18,sort:'curadoria'});const collectionLd={"@context":"https://schema.org","@type":"CollectionPage",name:`Tema ${theme.tag}`,description:`Seleção de papelaria personalizada com o tema ${theme.tag}.`,url:siteUrl?`${siteUrl}/temas/${slugifyText(theme.tag)}`:undefined,isPartOf:siteUrl?{"@type":"WebSite",name:settings.brand_name,url:siteUrl}:undefined};const breadcrumbLd={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:'Início',item:siteUrl||undefined},{"@type":"ListItem",position:2,name:`Tema ${theme.tag}`,item:siteUrl?`${siteUrl}/temas/${slugifyText(theme.tag)}`:undefined}]};return <main className="premium-site theme-premium-page"><Header settings={settings}/><JsonLd data={collectionLd}/><JsonLd data={breadcrumbLd}/><section className="theme-hero"><div className="container"><Link className="back-link" href="/#catalogo"><ArrowLeft size={16}/> Voltar ao catálogo</Link><div className="theme-kicker">TEMA EM DESTAQUE</div><h1>{theme.tag}</h1><p>Uma seleção de peças que compartilham esta linguagem visual. Combine categorias diferentes e monte um conjunto coerente para o evento.</p><div className="theme-meta"><span>{String(catalog.total).padStart(2,'0')} {catalog.total===1?'peça':'peças'}</span><i/><a href="#itens">Explorar tema <ArrowUpRight size={15}/></a></div></div></section><section className="theme-listing" id="itens"><div className="container"><div className="section-index"><span>01</span><i/><small>{theme.tag.toUpperCase()}</small></div><CatalogClient products={catalog.items} total={catalog.total} hasMore={catalog.has_more} categories={categories} fixedTag={theme.tag} whatsapp={settings.whatsapp_number}/></div></section><Footer settings={settings}/></main>;}
