import { hasRecentAdminReauthentication,isAdmin } from '@/lib/auth';
import { deleteInquiry,getInquiryById,InquiryCommercialStateError,logAdminAction,StaleWriteError,updateInquiry, requireCriticalAuditIntent } from '@/lib/db';
import { inquiryAdminSchema } from '@/lib/validation';
import { isUuid,readJsonBody,sameOriginRequest } from '@/lib/security';
import { serverFailure } from '@/lib/observability';
import { recordAdminSecurityEventWithAlert } from '@/lib/admin-security-alerts';
import { expectedVersionFromRequest } from '@/lib/concurrency';
function money(v:number|null){return v==null?'sem valor':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){
  if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401});if(!sameOriginRequest(request))return Response.json({error:'Origem inválida.'},{status:403});const{id}=await params;if(!isUuid(id))return Response.json({error:'ID inválido.'},{status:400});
  try{
    const body=await readJsonBody(request,24_000);const parsed=inquiryAdminSchema.safeParse(body);if(!parsed.success)return Response.json({error:'Dados do atendimento inválidos.'},{status:400});
    const expectedVersion=Number(body.expected_version);if(!Number.isInteger(expectedVersion)||expectedVersion<1)return Response.json({error:'A versão deste atendimento está ausente ou desatualizada. Recarregue antes de salvar.'},{status:409});
    const previous=await getInquiryById(id);if(!previous)return Response.json({error:'Orçamento não encontrado.'},{status:404});if(previous.version!==expectedVersion)throw new StaleWriteError();
    const updateInput={...parsed.data,payment_status:parsed.data.payment_status??previous.payment_status,paid_cents:parsed.data.paid_cents??previous.paid_cents,production_status:parsed.data.production_status??previous.production_status,production_due_at:parsed.data.production_due_at===undefined?previous.production_due_at:parsed.data.production_due_at};
    const changes:string[]=[];if(previous.status!==updateInput.status)changes.push(`Status: ${previous.status} → ${updateInput.status}`);if(previous.quoted_value_cents!==updateInput.quoted_value_cents)changes.push(`Valor: ${money(previous.quoted_value_cents)} → ${money(updateInput.quoted_value_cents)}`);if(previous.follow_up_at!==updateInput.follow_up_at)changes.push(updateInput.follow_up_at?`Follow-up definido para ${new Date(updateInput.follow_up_at).toLocaleString('pt-BR')}`:'Follow-up removido');if((previous.admin_notes||'')!==(updateInput.admin_notes||''))changes.push('Notas internas atualizadas');if(previous.payment_status!==updateInput.payment_status)changes.push(`Pagamento: ${previous.payment_status||'pendente'} → ${updateInput.payment_status}`);if(Number(previous.paid_cents||0)!==Number(updateInput.paid_cents||0))changes.push(`Valor recebido: ${money(Number(previous.paid_cents||0))} → ${money(Number(updateInput.paid_cents||0))}`);if(previous.production_status!==updateInput.production_status)changes.push(`Produção: ${previous.production_status||'nao_iniciado'} → ${updateInput.production_status}`);if(previous.production_due_at!==updateInput.production_due_at)changes.push(updateInput.production_due_at?`Prazo interno de produção: ${new Date(updateInput.production_due_at).toLocaleString('pt-BR')}`:'Prazo interno de produção removido');
    const inquiry=await updateInquiry(id,updateInput,expectedVersion,changes.join(' • ')||'Atendimento salvo.',{fields:changes.length,from_version:expectedVersion});if(!inquiry)return Response.json({error:'Orçamento não encontrado.'},{status:404});
    await logAdminAction('update','inquiry',id,`Atendimento atualizado para ${inquiry.status}.`,{metadata:{version:inquiry.version}});return Response.json({inquiry});
  }catch(e){if(e instanceof StaleWriteError)return Response.json({error:e.message,conflict:true},{status:409});if(e instanceof InquiryCommercialStateError)return Response.json({error:e.message,code:e.code},{status:422});return await serverFailure('admin.inquiries.update',e);}
}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401});if(!sameOriginRequest(request))return Response.json({error:'Origem inválida.'},{status:403});const{id}=await params;if(!isUuid(id))return Response.json({error:'ID inválido.'},{status:400});try{const expectedVersion=expectedVersionFromRequest(request);if(!(await hasRecentAdminReauthentication()))return Response.json({error:'Confirme novamente sua identidade para excluir este atendimento.',reauth_required:true},{status:428});await requireCriticalAuditIntent('delete_inquiry','inquiry',id,'Exclusão permanente de atendimento/orçamento autorizada após step-up MFA.');const deleted=await deleteInquiry(id,expectedVersion);if(!deleted)return Response.json({error:'Atendimento não encontrado.'},{status:404});await logAdminAction('delete','inquiry',id,'Orçamento excluído.');await recordAdminSecurityEventWithAlert({eventType:'critical_action',severity:'warning',summary:`Atendimento/orçamento excluído (${id}).`});return Response.json({ok:true});}catch(e){if(e instanceof StaleWriteError)return Response.json({error:e.message,conflict:true},{status:409});return await serverFailure('admin.inquiries.delete',e);}}
