import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowUpRight, CalendarDays, CheckCircle2, Gem, ImageIcon, Layers3, MessageCircle, PackagePlus, Palette, Scissors, ShieldCheck, Sparkles, Star, WandSparkles } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import MerlinMobileDock from '@/components/MerlinMobileDock';
import InspirationShowcase from '@/components/InspirationShowcase';
import { getCategories, getHomeCuratedProducts, getSiteSettings, getTestimonials } from '@/lib/db';
import { siteUrl } from '@/lib/config';
import { jsonLd } from '@/lib/seo';
import { inspirationModels } from '@/lib/inspirations';

export const dynamic='force-dynamic';
function digits(v:string){return v.replace(/\D/g,'');}
function HeroTitle({title,highlight}:{title:string;highlight:string}){const h=highlight.trim();const i=h?title.toLocaleLowerCase('pt-BR').indexOf(h.toLocaleLowerCase('pt-BR')):-1;if(i<0)return <>{title}</>;return <>{title.slice(0,i)}<span>{title.slice(i,i+h.length)}</span>{title.slice(i+h.length)}</>;}

export default async function HomePage(){
  const [products,categories,settings,testimonials]=await Promise.all([getHomeCuratedProducts(6),getCategories(),getSiteSettings(),getTestimonials()]);
  const phone=digits(settings.whatsapp_number);
  const wa=phone?`https://wa.me/${phone}?text=${encodeURIComponent('Olá! Vim pelo site da Merlin Encantos em Papel e gostaria de solicitar um orçamento personalizado.')}`:'';
  const referenceWa=phone?`https://wa.me/${phone}?text=${encodeURIComponent('Olá! Vim pelo site da Merlin Encantos em Papel. Já tenho uma foto ou print de referência e quero enviar para vocês me ajudarem a montar o orçamento.')}`:'';
  const previewProducts=products.filter(p=>p.image_urls.length>0).slice(0,4);
  const previewCategories=categories.slice(0,6);
  const organizationJsonLd={"@context":"https://schema.org","@type":"Store",name:settings.brand_name,url:siteUrl||undefined,description:settings.seo_description,logo:settings.logo_url||undefined,telephone:settings.whatsapp_number,email:settings.contact_email||undefined,areaServed:settings.location,sameAs:[settings.instagram_url,settings.facebook_url,settings.tiktok_url,settings.pinterest_url,settings.youtube_url,settings.google_business_url].filter(Boolean)};
  return <main className="premium-site kf-theme home-v672 home-v673">
    <Header settings={settings}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(organizationJsonLd)}}/>
    <section className="hero premium-hero kf-hero" id="inicio"><div className="hero-wordmark" aria-hidden="true">Merlin</div><div className="container hero-grid"><div className="hero-copy-column" data-reveal><div className="eyebrow"><i/> {settings.hero_eyebrow}</div><h1><HeroTitle title={settings.hero_title} highlight={settings.hero_highlight}/></h1><p className="hero-copy">{settings.hero_description}</p><div className="hero-actions"><Link className="btn btn-primary btn-luxury" href="/inspiracoes">Ver inspirações <Sparkles size={17}/></Link><Link className="btn btn-ghost" href="/orcamento">Pedir orçamento <ArrowUpRight size={16}/></Link>{wa&&<a className="home-hero-whatsapp" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={16}/> Falar no WhatsApp</a>}</div><div className="trust-row"><span><ShieldCheck size={15}/> Projeto personalizado</span><span><Sparkles size={15}/> Curadoria visual</span><span><WandSparkles size={15}/> Produção sob encomenda</span></div></div><div className="hero-visual kf-hero-visual" data-reveal><div className="hero-frame-line"/><div className="hero-card main kf-logo-card"><Image src={settings.logo_url||'/merlin-logo.webp'} alt={`${settings.brand_name} — logo`} fill priority quality={82} sizes="(max-width: 760px) 82vw, (max-width: 1100px) 48vw, 520px" style={{objectFit:'contain'}}/><span className="hero-image-label">MERLIN • ENCANTOS EM PAPEL</span></div><div className="hero-badge"><span>mais de</span><strong>{inspirationModels.length} ideias</strong><small>para começar</small></div></div></div><div className="hero-bottom container"><span>{inspirationModels.length} ideias de inspiração</span><span>{categories.length} coleções</span><span>{settings.location}</span></div></section>
    <section className="signature-strip" aria-label="Diferenciais"><div className="signature-track"><span>FEITO SOB ENCOMENDA</span><i/><span>TOPOS DE BOLO</span><i/><span>CAIXAS PERSONALIZADAS</span><i/><span>KITS DE FESTA</span><i/><span>LEMBRANCINHAS</span><i/><span>MERLIN • ENCANTOS EM PAPEL</span></div></section>
    <InspirationShowcase whatsapp={settings.whatsapp_number} limit={6} compact/>
    <section className="category-showcase premium-categories home-categories" id="colecoes"><div className="container"><div className="section-index" data-reveal><span>02</span><i/><small>COLEÇÕES</small></div><div className="catalog-head" data-reveal><div><div className="eyebrow">Encontre mais rápido</div><h2 className="section-title">Escolha a peça.<br/><em>Sem rolar uma eternidade.</em></h2></div><p className="muted">As categorias principais ficam aqui. O catálogo completo continua disponível com busca e filtros.</p></div><div className="category-grid editorial-grid home-category-grid">{previewCategories.map((c,i)=><Link className="category-card editorial-category" href={`/categorias/${c.slug}`} key={c.id} data-reveal><div className="category-card-art">{c.image_url?<Image src={c.image_url} alt="" fill quality={76} sizes="(max-width: 760px) 88vw, (max-width: 1100px) 46vw, 33vw" style={{objectFit:'cover'}}/>:<span>{String(i+1).padStart(2,'0')}</span>}<div className="category-overlay"/></div><div className="category-copy"><small>{String(i+1).padStart(2,'0')}</small><strong>{c.name}</strong><span className="category-link">Ver coleção <ArrowUpRight size={15}/></span></div></Link>)}</div><div className="home-section-action"><a href="#catalogo" className="text-link">Ver seleção de produtos <ArrowDown size={15}/></a></div></div></section>
    <section className="event-pathways kf-order-pathways home-start" id="concierge" aria-labelledby="event-pathways-title"><div className="container"><div className="section-index" data-reveal><span>03</span><i/><small>COMECE AQUI</small></div><div className="event-pathways-shell" data-reveal><div className="event-pathways-copy"><div className="eyebrow">Escolha só o que faz sentido agora</div><h2 id="event-pathways-title">Três caminhos.<br/><em>Um pedido mais simples.</em></h2><p>Você não precisa conhecer todos os produtos nem decidir tudo de uma vez. Comece pela opção que combina com o que já sabe.</p></div><div className="event-pathways-primary"><Link href="/inspiracoes"><small>01 • QUERO IDEIAS</small><strong>Explorar inspirações</strong><span>Ver modelos <ArrowUpRight size={15}/></span></Link><Link href="/monte-seu-kit"><small>02 • SEI O QUE PRECISO</small><strong>Montar meu kit</strong><span>Montar pedido <ArrowUpRight size={15}/></span></Link><Link href="/orcamento"><small>03 • QUERO AJUDA</small><strong>Pedir orientação</strong><span>Fazer orçamento <ArrowUpRight size={15}/></span></Link>{referenceWa&&<a className="event-pathway-reference" href={referenceWa} target="_blank" rel="noreferrer"><ImageIcon size={18}/><div><strong>Já tenho uma foto ou referência</strong><span>Enviar direto pelo WhatsApp</span></div><ArrowUpRight size={16}/></a>}</div></div></div></section>
    <section className="home-catalog-preview" id="catalogo"><div className="container"><div className="section-index" data-reveal><span>04</span><i/><small>CATÁLOGO</small></div><div className="home-preview-head" data-reveal><div><div className="eyebrow">Seleção rápida</div><h2 className="section-title">Veja algumas peças.<br/><em>Abra o catálogo quando quiser.</em></h2></div><div className="home-preview-actions"><Link className="btn btn-primary" href="/catalogo">Ver catálogo completo <ArrowUpRight size={16}/></Link><Link className="btn btn-ghost" href="/guia-de-precos">Consultar preços</Link></div></div><div className="home-product-grid">{previewProducts.map((p,i)=><Link className="home-product-card" href={`/catalogo/${p.slug}`} key={p.id} data-reveal><div className="home-product-image"><Image src={p.image_urls[0]||settings.logo_url||'/merlin-logo.webp'} alt={p.name} fill quality={76} sizes="(max-width: 760px) 84vw, (max-width: 1100px) 44vw, 25vw" style={{objectFit:'cover'}}/><span>{String(i+1).padStart(2,'0')}</span></div><div><small>{p.category}</small><strong>{p.name}</strong><span>Ver detalhes <ArrowUpRight size={14}/></span></div></Link>)}</div></div></section>
    <section className="craft-section home-craft" id="sobre"><div className="container"><div className="section-index" data-reveal><span>05</span><i/><small>ATELIÊ</small></div><div className="craft-head" data-reveal><div><div className="eyebrow">Do conceito ao acabamento</div><h2>{settings.about_title}</h2></div><p>{settings.about_text}</p></div><div className="craft-grid"><article data-reveal><span>01</span><Gem/><h3>Direção visual</h3><p>Tema, cores e tipografia trabalhando juntos.</p></article><article data-reveal><span>02</span><Layers3/><h3>Camadas</h3><p>Volume e profundidade sem poluir a composição.</p></article><article data-reveal><span>03</span><Scissors/><h3>Precisão</h3><p>Corte e montagem com alinhamento e acabamento limpo.</p></article><article data-reveal><span>04</span><Sparkles/><h3>Finalização</h3><p>Detalhes pensados para a mesa e para as fotos.</p></article></div><span className="merlin-stamp" aria-hidden="true">MERLIN</span></div></section>
    {testimonials.length>0&&<section className="testimonial-section home-testimonials"><div className="container"><div className="section-index" data-reveal><span>06</span><i/><small>CLIENTES</small></div><div className="home-testimonial-layout"><div data-reveal><div className="eyebrow">Experiências reais</div><h2 className="section-title">Cuidado que aparece<br/><em>no resultado.</em></h2></div><div className="testimonial-grid">{testimonials.slice(0,3).map(t=><article key={t.id} data-reveal><div className="testimonial-stars" aria-label={`${t.rating} de 5 estrelas`}>{Array.from({length:t.rating}).map((_,n)=><Star size={13} fill="currentColor" key={n}/>)}</div><blockquote>“{t.quote}”</blockquote><footer><div><strong>{t.name}</strong>{t.location&&<small>{t.location}</small>}</div></footer></article>)}</div></div></div></section>}
    <section className="merlin-briefing-section home-briefing" id="processo" aria-labelledby="merlin-briefing-title"><div className="container"><div className="merlin-briefing-shell" data-reveal><div className="merlin-briefing-copy"><div className="eyebrow"><CheckCircle2 size={14}/> Para pedir sem complicação</div><h2 id="merlin-briefing-title">Passe o essencial.<br/><em>A gente organiza o resto.</em></h2><p>Um briefing curto já ajuda a transformar sua ideia em um orçamento muito mais claro.</p><div className="merlin-briefing-actions"><Link className="btn btn-primary" href="/monte-seu-kit">Montar briefing <PackagePlus size={16}/></Link></div></div><div className="merlin-briefing-grid"><article><CalendarDays/><strong>Data do evento</strong></article><article><Palette/><strong>Tema e cores</strong></article><article><PackagePlus/><strong>Peças e quantidades</strong></article><article><ImageIcon/><strong>Referências</strong></article></div></div></div></section>
    <section className="premium-cta home-final-cta" id="contato"><div className="container"><div className="cta-box" data-reveal><div><div className="eyebrow">Atendimento direto</div><h2>Seu projeto pode<br/><em>começar agora.</em></h2><p>Envie sua ideia, data do evento e quantidade. O orçamento continua personalizado.</p></div><div className="home-final-actions"><Link className="btn btn-primary btn-luxury" href="/orcamento">Pedir orçamento <ArrowUpRight size={16}/></Link>{wa&&<a className="btn btn-ghost" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Abrir WhatsApp</a>}</div></div></div></section>
    <MerlinMobileDock whatsapp={settings.whatsapp_number}/><Footer settings={settings}/>
  </main>;
}
