import Link from 'next/link';
import { ArrowUpRight, CheckCircle2, Layers3, MessageCircle, Scissors, Sparkles, Star } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import TopperLevelVisual from '@/components/TopperLevelVisual';
import MerlinMobileDock from '@/components/MerlinMobileDock';
import JsonLd from '@/components/JsonLd';
import { getSiteSettings, getTestimonials } from '@/lib/db';
import { siteUrl } from '@/lib/config';
import { topperLevels, topperThemes } from '@/lib/topper-catalog';

export const dynamic='force-dynamic';
function digits(v:string){return v.replace(/\D/g,'');}

export default async function HomePage(){
  const [settings,testimonials]=await Promise.all([getSiteSettings(),getTestimonials()]);
  const phone=digits(settings.whatsapp_number);
  const wa=phone?`https://wa.me/${phone}?text=${encodeURIComponent('Olá! Vim pelo site da Merlin Encantos em Papel e gostaria de pedir um orçamento para um topo de bolo personalizado.')}`:'';
  const organizationJsonLd={"@context":"https://schema.org","@type":"Store",name:settings.brand_name,url:siteUrl||undefined,description:'Topos de bolo personalizados sob encomenda, do simples ao Elite com shaker e acetato.',logo:settings.logo_url||undefined,telephone:settings.whatsapp_number,areaServed:settings.location};
  return <main className="premium-site kf-theme home-v672 home-v673 home-v680 public-v712">
    <Header settings={settings}/><JsonLd data={organizationJsonLd}/>

    <section className="hero premium-hero kf-hero" id="inicio"><div className="container hero-grid"><div className="hero-copy-column" data-reveal>
      <div className="eyebrow"><i/> MERLIN • TOPOS DE BOLO PERSONALIZADOS</div>
      <h1>Seu tema, do seu jeito.<br/><span>Do simples ao Elite.</span></h1>
      <p className="hero-copy">Use o site como mostruário para entender estilos, níveis de acabamento e possibilidades. Você escolhe uma referência; nome, idade, cores e composição são adaptados ao seu pedido.</p>
      <div className="hero-actions"><Link className="btn btn-primary btn-luxury" href="/inspiracoes">Ver inspirações <Sparkles size={17}/></Link><Link className="btn btn-ghost" href="/catalogo">Conhecer os níveis <Layers3 size={16}/></Link>{wa&&<a className="home-hero-whatsapp" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={16}/> Falar no WhatsApp</a>}</div>
      <div className="trust-row"><span><CheckCircle2 size={15}/> Referências para você escolher com calma</span><span><Scissors size={15}/> Nome, idade e cores personalizados</span><span><Sparkles size={15}/> Orçamento confirmado antes da produção</span></div>
    </div><div className="hero-visual kf-hero-visual" data-reveal><div className="hero-card main kf-logo-card"><img src={settings.logo_url||'/merlin-logo.webp'} alt={settings.brand_name}/><span className="hero-image-label">MERLIN • ENCANTOS EM PAPEL</span></div><div className="hero-badge"><span>linha com</span><strong>{topperLevels.length} níveis</strong><small>Elite com shaker e acetato</small></div></div></div></section>

    <section className="category-showcase premium-categories home-categories" id="topos"><div className="container">
      <div className="section-index" data-reveal><span>01</span><i/><small>NÍVEIS DE TOPO</small></div>
      <div className="catalog-head" data-reveal><div><div className="eyebrow">Escolha pelo acabamento</div><h2 className="section-title">Escolha quanto detalhe<br/><em>você quer no resultado.</em></h2><Link className="public-inline-guide" href="/guia-de-precos">Entender níveis & preços <ArrowUpRight size={14}/></Link></div><p className="muted">Do visual mais limpo às composições com várias camadas, shaker e acetato. Cada nível mostra até onde podemos levar o acabamento.</p></div>
      <div className="category-grid editorial-grid home-category-grid">{topperLevels.map((level,i)=><Link className="category-card editorial-category" href={`/catalogo/${level.slug}`} key={level.slug} data-reveal><div className="category-card-art public-level-art"><TopperLevelVisual level={level} compact/><span>{level.code}</span><div className="category-overlay"/></div><div className="category-copy"><small>{String(i+1).padStart(2,'0')}</small><strong>{level.name}</strong><span>{level.complexity}</span><span className="category-link">Ver detalhes <ArrowUpRight size={15}/></span></div></Link>)}</div>
    </div></section>

    <section className="event-pathways kf-order-pathways home-start"><div className="container"><div className="section-index" data-reveal><span>02</span><i/><small>COMO PEDIR</small></div><div className="event-pathways-shell" data-reveal><div className="event-pathways-copy"><div className="eyebrow">Um caminho simples</div><h2>Inspire-se.<br/><em>Personalize. Peça orçamento.</em></h2><p>Você não precisa chegar com tudo decidido. Escolha uma referência, diga o que quer mudar e envie as informações essenciais.</p></div><div className="event-pathways-primary"><Link href="/inspiracoes"><small>01 • INSPIRE-SE</small><strong>Encontre uma referência que combine com você</strong><span>Ver ideias <ArrowUpRight size={15}/></span></Link><Link href="/catalogo"><small>02 • PERSONALIZE</small><strong>Escolha o nível de acabamento</strong><span>Comparar níveis <ArrowUpRight size={15}/></span></Link><Link href="/monte-seu-topo"><small>03 • ORÇAMENTO</small><strong>Conte como você quer o seu topo</strong><span>Enviar briefing <ArrowUpRight size={15}/></span></Link></div></div></div></section>

    <section className="home-catalog-preview"><div className="container"><div className="section-index" data-reveal><span>03</span><i/><small>TEMAS</small></div><div className="home-preview-head" data-reveal><div><div className="eyebrow">Estilos para se inspirar</div><h2 className="section-title">Use as referências para<br/><em>explicar o que você imagina.</em></h2></div><Link className="btn btn-primary" href="/inspiracoes">Ver inspirações <ArrowUpRight size={16}/></Link></div><div className="craft-grid">{topperThemes.slice(0,8).map((theme,i)=><article key={theme.slug} data-reveal><span>{String(i+1).padStart(2,'0')}</span><Sparkles/><h3>{theme.label}</h3><p>{theme.description}</p></article>)}</div></div></section>

    <section className="craft-section home-craft"><div className="container"><div className="section-index" data-reveal><span>04</span><i/><small>ACABAMENTO</small></div><div className="craft-head" data-reveal><div><div className="eyebrow">Acabamento visível no resultado</div><h2>Detalhes com propósito.</h2></div><p>Camadas, shaker e acetato só entram quando ajudam a composição. O objetivo é deixar o topo bonito, legível e adequado ao tamanho do bolo.</p></div><div className="craft-grid"><article><span>01</span><Scissors/><h3>Recorte limpo</h3><p>Peças pensadas para produção real.</p></article><article><span>02</span><Layers3/><h3>Camadas com função</h3><p>Profundidade sem perder leitura.</p></article><article><span>03</span><Sparkles/><h3>Shaker</h3><p>Movimento controlado e acabamento fechado.</p></article><article><span>04</span><Sparkles/><h3>Acetato</h3><p>Efeito suspenso e leve nos modelos avançados.</p></article></div></div></section>

    <section className="public-home-about" id="sobre"><div className="container public-home-split"><div><div className="eyebrow">Sobre a Merlin</div><h2>Topo personalizado, pensado para o seu bolo.</h2></div><div><p>A Merlin Encantos em Papel trabalha com topos de bolo sob encomenda. Este site funciona como um mostruário visual para você conhecer estilos, níveis de acabamento e possibilidades antes de pedir.</p><p>As inspirações são pontos de partida: cores, nome, idade, elementos e acabamento podem ser adaptados para combinar com o seu bolo e com a sua ideia.</p></div></div></section>

    <section className="public-home-faq" id="duvidas"><div className="container"><div className="eyebrow">Dúvidas frequentes</div><h2>Antes de pedir, vale saber.</h2><div className="public-home-faq-grid"><details><summary>Posso mudar as cores de uma inspiração?</summary><p>Sim. Nome, idade, cores e detalhes podem ser adaptados ao seu pedido.</p></details><details><summary>Preciso escolher o nível sugerido da inspiração?</summary><p>Não. O nível sugerido é apenas um ponto de partida; você pode escolher outro acabamento no formulário.</p></details><details><summary>Shaker e acetato entram em qualquer topo?</summary><p>São acabamentos avançados usados quando combinam com a composição e com o nível escolhido.</p></details><details><summary>Como recebo o valor?</summary><p>O orçamento considera nível, complexidade do tema, materiais, tamanho e prazo. O site não faz pagamento automático.</p></details></div></div></section>

    <section className="public-home-contact" id="contato"><div className="container public-home-contact-card"><div><div className="eyebrow">Contato</div><h2>Já encontrou uma referência que gostou?</h2><p>Envie o briefing pelo site ou fale direto no WhatsApp. Antes de qualquer produção, você recebe o orçamento e confirma os detalhes.</p></div><div className="public-home-contact-actions"><Link className="btn btn-primary btn-luxury" href="/monte-seu-topo">Enviar meu briefing <ArrowUpRight size={16}/></Link><Link className="btn btn-ghost" href="/orcamento">Pedir orçamento</Link>{wa&&<a className="btn btn-ghost" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={17}/> WhatsApp</a>}{settings.contact_email&&<a className="btn btn-ghost" href={`mailto:${settings.contact_email}`}>{settings.contact_email}</a>}</div></div></section>

    {testimonials.length>0&&<section className="testimonial-section home-testimonials"><div className="container"><div className="section-index" data-reveal><span>05</span><i/><small>CLIENTES</small></div><div className="testimonial-grid">{testimonials.slice(0,3).map(t=><article key={t.id}><div className="testimonial-stars">{Array.from({length:t.rating}).map((_,n)=><Star size={13} fill="currentColor" key={n}/>)}</div><blockquote>“{t.quote}”</blockquote><footer><strong>{t.name}</strong></footer></article>)}</div></div></section>}

    <section className="premium-cta home-final-cta"><div className="container"><div className="cta-box" data-reveal><div><div className="eyebrow">Seu topo começa por uma referência</div><h2>Escolha o que você gosta.<br/><em>Depois a gente adapta.</em></h2><p>Envie tema, nome, idade, cores, tamanho do bolo e qualquer referência que ajude a explicar a sua ideia.</p></div><div className="home-final-actions"><Link className="btn btn-primary btn-luxury" href="/monte-seu-topo">Montar meu topo <ArrowUpRight size={16}/></Link>{wa&&<a className="btn btn-ghost" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={17}/> WhatsApp</a>}</div></div></div></section>
    <MerlinMobileDock whatsapp={settings.whatsapp_number}/><Footer settings={settings}/>
  </main>;
}
