import { ArrowDown, ArrowUpRight, CalendarDays, CheckCircle2, Gem, ImageIcon, Layers3, MessageCircle, PackagePlus, Palette, Scissors, ShieldCheck, Sparkles, Star, WandSparkles } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import MerlinMobileDock from '@/components/MerlinMobileDock';
import InspirationShowcase from '@/components/InspirationShowcase';
import CatalogClient from '@/components/CatalogClient';
import QuoteForm from '@/components/QuoteForm';
import PartyConcierge from '@/components/PartyConcierge';
import RecentlyViewed from '@/components/RecentlyViewed';
import SafeImage from '@/components/SafeImage';
import StarterPriceGuide from '@/components/StarterPriceGuide';
import OrderDecisionGuide from '@/components/OrderDecisionGuide';
import { getCategories, getFaqs, getHomeCuratedProducts, getPublicCatalogPage, getPublicCategoryCounts, getPublicPopularTags, getSiteSettings, getTestimonials } from '@/lib/db';
import { siteUrl } from '@/lib/config';
import { jsonLd } from '@/lib/seo';
import { inspirationModels } from '@/lib/inspirations';
export const dynamic='force-dynamic';
function digits(v:string){return v.replace(/\D/g,'');}
function HeroTitle({title,highlight}:{title:string;highlight:string}){const h=highlight.trim();const i=h?title.toLocaleLowerCase('pt-BR').indexOf(h.toLocaleLowerCase('pt-BR')):-1;if(i<0)return <>{title}</>;return <>{title.slice(0,i)}<span>{title.slice(i,i+h.length)}</span>{title.slice(i+h.length)}</>;}
export default async function HomePage(){
  const [products,firstCatalog,categories,categoryCounts,popularTags,settings,testimonials,faqs]=await Promise.all([getHomeCuratedProducts(18),getPublicCatalogPage({page:1,pageSize:18,sort:'curadoria'}),getCategories(),getPublicCategoryCounts(),getPublicPopularTags(8),getSiteSettings(),getTestimonials(),getFaqs()]);
  const phone=digits(settings.whatsapp_number);const wa=phone?`https://wa.me/${phone}?text=${encodeURIComponent('Olá! Vim pelo catálogo da Merlin Encantos em Papel e gostaria de solicitar um orçamento personalizado.')}`:'';const referenceWa=phone?`https://wa.me/${phone}?text=${encodeURIComponent('Olá! Vim pelo site da Merlin Encantos em Papel. Já tenho uma foto ou print de referência e quero enviar para vocês me ajudarem a montar o orçamento.')}`:'';
  const featured=products.filter(p=>p.featured).slice(0,3);const lookbook=products.filter(p=>p.image_urls.length>0).slice(0,6);
  let nextSection=4;const featuredIndex=featured.length?nextSection++:null;const lookbookIndex=lookbook.length>2?nextSection++:null;const conciergeIndex=nextSection++;const catalogIndex=nextSection++;const craftIndex=nextSection++;const testimonialIndex=testimonials.length?nextSection++:null;const processIndex=nextSection++;const faqIndex=faqs.length?nextSection++:null;const contactIndex=nextSection++;const sectionLabel=(n:number|null)=>String(n||0).padStart(2,'0');
  const organizationJsonLd={"@context":"https://schema.org","@type":"Store",name:settings.brand_name,url:siteUrl||undefined,description:settings.seo_description,logo:settings.logo_url||undefined,telephone:settings.whatsapp_number,email:settings.contact_email||undefined,areaServed:settings.location,sameAs:[settings.instagram_url,settings.facebook_url,settings.tiktok_url,settings.pinterest_url,settings.youtube_url,settings.google_business_url].filter(Boolean)};
  const faqJsonLd=faqs.length?{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))}:null;
  return <main className="premium-site kf-theme"><Header settings={settings}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(organizationJsonLd)}}/>{faqJsonLd&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(faqJsonLd)}}/>}
    <section className="hero premium-hero kf-hero" id="inicio"><div className="hero-wordmark" aria-hidden="true">Merlin</div><div className="container hero-grid"><div className="hero-copy-column" data-reveal><div className="eyebrow"><i/> {settings.hero_eyebrow}</div><h1><HeroTitle title={settings.hero_title} highlight={settings.hero_highlight}/></h1><p className="hero-copy">{settings.hero_description}</p><div className="hero-actions"><a className="btn btn-primary btn-luxury" href="/inspiracoes">Ver inspirações <Sparkles size={17}/></a><a className="btn btn-ghost" href="/monte-seu-kit">Monte seu kit <PackagePlus size={17}/></a><a className="btn btn-ghost" href="#concierge">Quero sugestões <ArrowDown size={17}/></a>{wa&&<a className="btn btn-ghost" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={17}/> WhatsApp</a>}</div><div className="trust-row"><span><ShieldCheck size={15}/> Projeto personalizado</span><span><Sparkles size={15}/> Modelos para inspirar</span><span><WandSparkles size={15}/> Produção sob encomenda</span></div></div><div className="hero-visual kf-hero-visual" data-reveal><div className="hero-frame-line"/><div className="hero-card back kf-hero-note"><div className="hero-art"><small>ESCOLHA SEU CAMINHO</small><strong>Inspire-se.<br/>Misture ideias.<br/>Personalize.</strong></div></div><div className="hero-card main kf-logo-card"><SafeImage src={settings.logo_url||'/merlin-logo.webp'} alt={`${settings.brand_name} — logo`} fetchPriority="high" decoding="async"/><span className="hero-image-label">MERLIN • ENCANTOS EM PAPEL</span></div><div className="hero-badge"><span>mais de</span><strong>{inspirationModels.length} ideias</strong><small>para começar</small></div></div></div><div className="hero-bottom container"><span>{String(inspirationModels.length).padStart(2,'0')} modelos de inspiração</span><span>{String(categories.length).padStart(2,'0')} coleções atuais</span><span>{settings.location}</span></div></section>
    <section className="signature-strip" aria-label="Diferenciais"><div className="signature-track"><span>FEITO SOB ENCOMENDA</span><i/> <span>TOPOS DE BOLO</span><i/> <span>CAIXAS PERSONALIZADAS</span><i/> <span>KITS DE FESTA</span><i/> <span>LEMBRANCINHAS</span><i/> <span>DETALHES QUE CONTAM HISTÓRIAS</span><i/> <span>MERLIN • ENCANTOS EM PAPEL</span></div></section>
    <InspirationShowcase whatsapp={settings.whatsapp_number} limit={12}/>
    <section className="category-showcase premium-categories" id="colecoes"><div className="container"><div className="section-index" data-reveal><span>02</span><i/><small>COLEÇÕES</small></div><div className="catalog-head" data-reveal><div><div className="eyebrow">Navegue por categoria</div><h2 className="section-title">Peças pensadas<br/><em>como coleção.</em></h2></div><p className="muted">Da peça principal aos detalhes de mesa, cada categoria foi organizada para facilitar a escolha e manter uma identidade visual consistente.</p></div><div className="category-grid editorial-grid">{categories.map((c,i)=><a className="category-card editorial-category" href={`/categorias/${c.slug}`} key={c.id} data-reveal><div className="category-card-art">{c.image_url?<SafeImage src={c.image_url} alt="" loading="lazy" decoding="async"/>:<span>{String(i+1).padStart(2,'0')}</span>}<div className="category-overlay"/></div><div className="category-copy"><small>{String(i+1).padStart(2,'0')} / {String(categories.length).padStart(2,'0')} • {(categoryCounts[c.name]||0)>0?`${categoryCounts[c.name]} ${(categoryCounts[c.name]||0)===1?'peça':'peças'}`:'aceita personalização'}</small><strong>{c.name}</strong>{c.description&&<p>{c.description}</p>}<span className="category-link">Ver coleção <ArrowUpRight size={16}/></span></div></a>)}</div></div></section>
    <section className="event-pathways kf-order-pathways" aria-labelledby="event-pathways-title"><div className="container"><div className="section-index" data-reveal><span>03</span><i/><small>COMO COMEÇAR</small></div><div className="event-pathways-shell" data-reveal><div className="event-pathways-copy"><div className="eyebrow">Escolha o caminho mais fácil para você</div><h2 id="event-pathways-title">Três jeitos rápidos<br/><em>de começar bem.</em></h2><p>Você não precisa chegar com tudo decidido. Escolha o ponto de partida que combina com o que já sabe hoje e refine o restante durante o pedido.</p><div className="event-pathways-shortcuts"><a href="/?occasion=Aniversário infantil#concierge">Começar pelo evento</a><a href="/#catalogo">Escolher por produto</a><a href="/?budget=150-300#concierge">Começar pelo orçamento</a><a href="/#contato">Enviar ideia livre</a></div></div><div className="event-pathways-primary"><a href="/inspiracoes"><small>01 • JÁ QUERO VER IDEIAS</small><strong>Explorar inspirações</strong><p>Filtre por tema, ocasião, estilo, paleta e nível de composição.</p><span>Ver modelos <ArrowUpRight size={15}/></span></a><a href="/monte-seu-kit"><small>02 • JÁ SEI O QUE PRECISO</small><strong>Montar meu kit</strong><p>Escolha peças, quantidades e referências em um briefing organizado.</p><span>Montar pedido <ArrowUpRight size={15}/></span></a><a href="#concierge"><small>03 • QUERO AJUDA PARA DECIDIR</small><strong>Receber sugestões</strong><p>Informe ocasião, tema, convidados e faixa de investimento para receber caminhos de composição.</p><span>Montar minha festa <ArrowDown size={15}/></span></a>{referenceWa&&<a className="event-pathway-reference" href={referenceWa} target="_blank" rel="noreferrer"><ImageIcon size={18}/><div><strong>Já tenho uma foto ou referência</strong><span>Envie direto pelo WhatsApp</span></div><ArrowUpRight size={16}/></a>}</div></div></div></section>
    <StarterPriceGuide whatsapp={settings.whatsapp_number}/>
    <OrderDecisionGuide/>
    {featured.length>0&&<section className="featured-editorial"><div className="container"><div className="section-index" data-reveal><span>{sectionLabel(featuredIndex)}</span><i/><small>SELEÇÃO</small></div><div className="featured-layout"><div className="featured-intro" data-reveal><div className="eyebrow">Curadoria do ateliê</div><h2>Detalhes que<br/><em>merecem destaque.</em></h2><p>Uma seleção de peças para mostrar de perto composição, acabamento e possibilidades de personalização.</p><a href="#catalogo" className="text-link">Ver catálogo completo <ArrowUpRight size={16}/></a></div><div className="featured-stack">{featured.map((p,i)=><a className={`featured-piece fp-${i+1}`} href={`/catalogo/${p.slug}`} key={p.id} data-reveal><div><SafeImage src={p.image_urls[0]} alt={p.name} loading="lazy" decoding="async"/></div><span>{String(i+1).padStart(2,'0')}</span><strong>{p.name}</strong><small>{p.category}</small></a>)}</div></div></div></section>}
    {lookbook.length>2&&<section className="lookbook-section"><div className="container"><div className="section-index" data-reveal><span>{sectionLabel(lookbookIndex)}</span><i/><small>LOOKBOOK</small></div><div className="lookbook-head" data-reveal><div><div className="eyebrow">Visão de conjunto</div><h2 className="section-title">Um catálogo para<br/><em>ver com calma.</em></h2></div><p>Explore detalhes, proporções e diferentes linguagens visuais. No celular, deslize horizontalmente como em um editorial.</p></div></div><div className="lookbook-rail" aria-label="Lookbook de produtos">{lookbook.map((p,i)=><a href={`/catalogo/${p.slug}`} className={`lookbook-card lookbook-${i+1}`} key={p.id}><div><SafeImage src={p.image_urls[0]} alt={p.name} loading="lazy" decoding="async"/></div><span>{String(i+1).padStart(2,'0')}</span><strong>{p.name}</strong><small>{p.category}</small></a>)}</div></section>}
    <PartyConcierge categories={categories} whatsapp={settings.whatsapp_number} sectionIndex={sectionLabel(conciergeIndex)}/><RecentlyViewed/>
    <section className="catalog-section premium-catalog" id="catalogo"><div className="container"><div className="section-index" data-reveal><span>{sectionLabel(catalogIndex)}</span><i/><small>CATÁLOGO</small></div><div className="catalog-head" data-reveal><div><div className="eyebrow">Catálogo completo</div><h2 className="section-title">Encontre a peça.<br/><em>Monte sua seleção.</em></h2></div><p className="muted">Adicione vários itens à sua lista de orçamento, ajuste as quantidades e envie tudo de uma vez. Ideal para montar o conjunto completo da festa.</p></div><CatalogClient products={firstCatalog.items} total={firstCatalog.total} hasMore={firstCatalog.has_more} categories={categories} popularTags={popularTags} whatsapp={settings.whatsapp_number}/></div></section>
    <section className="craft-section" id="sobre"><div className="container"><div className="section-index" data-reveal><span>{sectionLabel(craftIndex)}</span><i/><small>ATELIÊ</small></div><div className="craft-head" data-reveal><div><div className="eyebrow">Do conceito ao acabamento</div><h2>{settings.about_title}</h2></div><p>{settings.about_text}</p></div><div className="craft-grid"><article data-reveal><span>01</span><Gem/><h3>Direção visual</h3><p>Composição, proporção, tipografia e cores trabalhadas para o tema parecer coeso — não apenas decorado.</p></article><article data-reveal><span>02</span><Layers3/><h3>Camadas</h3><p>Volume e profundidade usados com intenção, valorizando leitura, hierarquia e presença da peça na mesa.</p></article><article data-reveal><span>03</span><Scissors/><h3>Precisão</h3><p>Corte e montagem planejados para manter alinhamento, contorno limpo e acabamento consistente.</p></article><article data-reveal><span>04</span><Sparkles/><h3>Finalização</h3><p>Detalhes finais pensados para a peça funcionar de perto, nas fotos e na composição completa da festa.</p></article></div></div></section>
    <section className="manifesto-section"><div className="container manifesto-grid"><div className="manifesto-number">MERLIN</div><div data-reveal><div className="eyebrow">Manifesto</div><blockquote>“Não é só papelaria.<br/>É a <em>assinatura visual</em><br/>da sua comemoração.”</blockquote><p>O objetivo é que cada peça tenha presença, acabamento e coerência suficientes para fazer parte da memória visual do evento.</p></div></div></section>
    {testimonials.length>0&&<section className="testimonial-section"><div className="container"><div className="section-index" data-reveal><span>{sectionLabel(testimonialIndex)}</span><i/><small>CLIENTES</small></div><div className="testimonial-head" data-reveal><div><div className="eyebrow">Experiências reais</div><h2 className="section-title">O acabamento aparece.<br/><em>O cuidado também.</em></h2></div><p>Depoimentos publicados diretamente pelo painel administrativo.</p></div><div className="testimonial-grid">{testimonials.slice(0,6).map((t,i)=><article key={t.id} data-reveal><div className="testimonial-stars" aria-label={`${t.rating} de 5 estrelas`}>{Array.from({length:t.rating}).map((_,n)=><Star size={14} fill="currentColor" key={n}/>)}</div><blockquote>“{t.quote}”</blockquote><footer><span>{String(i+1).padStart(2,'0')}</span><div><strong>{t.name}</strong>{t.location&&<small>{t.location}</small>}</div></footer></article>)}</div></div></section>}
    <section className="process premium-process" id="processo"><div className="container"><div className="section-index" data-reveal><span>{sectionLabel(processIndex)}</span><i/><small>PROCESSO</small></div><div className="catalog-head" data-reveal><div><div className="eyebrow">Como funciona</div><h2 className="section-title">Do primeiro contato<br/><em>à peça pronta.</em></h2></div><p className="muted">Um fluxo simples para transformar referência, tema e informações do evento em uma produção personalizada.</p></div><div className="process-grid"><div className="process-card" data-reveal><span className="process-num">01 — CURADORIA</span><h3>Escolha referências</h3><p>Adicione produtos à sua lista e monte o conjunto que deseja orçar.</p></div><div className="process-card" data-reveal><span className="process-num">02 — PERSONALIZAÇÃO</span><h3>Defina os detalhes</h3><p>Informe tema, nome, idade, cores, quantidade, data do evento e referências importantes.</p></div><div className="process-card" data-reveal><span className="process-num">03 — PRODUÇÃO</span><h3>Aprovação e acabamento</h3><p>Com o pedido definido, seguimos para produção, corte, montagem e finalização cuidadosa.</p></div></div></div></section>
    {faqs.length>0&&<section className="faq-section premium-faq"><div className="container faq-grid"><div data-reveal><div className="section-index compact"><span>{sectionLabel(faqIndex)}</span><i/><small>FAQ</small></div><div className="eyebrow">Dúvidas frequentes</div><h2 className="section-title">Antes<br/><em>de pedir.</em></h2><p className="muted">As condições exatas dependem do produto, quantidade e data do evento.</p></div><div className="faq-list" data-reveal>{faqs.map(f=><details key={f.id}><summary>{f.question}</summary><p>{f.answer}</p></details>)}</div></div></section>}
    <section className="merlin-briefing-section" aria-labelledby="merlin-briefing-title"><div className="container"><div className="merlin-briefing-shell" data-reveal><div className="merlin-briefing-copy"><div className="eyebrow"><CheckCircle2 size={14}/> Para agilizar seu orçamento</div><h2 id="merlin-briefing-title">Um bom briefing<br/><em>economiza idas e voltas.</em></h2><p>Não precisa ter tudo definido. Mas, quando essas informações já vêm juntas, fica mais fácil entender o projeto e orientar as próximas escolhas.</p><div className="merlin-briefing-actions"><a className="btn btn-primary" href="/monte-seu-kit">Montar briefing <PackagePlus size={16}/></a>{wa&&<a className="btn btn-ghost" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={16}/> Enviar pelo WhatsApp</a>}</div></div><div className="merlin-briefing-grid"><article><CalendarDays/><span>01</span><strong>Data do evento</strong><p>Ajuda a organizar o atendimento e verificar o contexto do pedido.</p></article><article><Palette/><span>02</span><strong>Tema e cores</strong><p>Pode ser uma ideia fechada ou apenas uma direção visual.</p></article><article><PackagePlus/><span>03</span><strong>Peças e quantidades</strong><p>Topo, caixas, lembranças, tags, displays ou um kit completo.</p></article><article><ImageIcon/><span>04</span><strong>Referências</strong><p>Fotos, prints ou modelos favoritos ajudam a alinhar o estilo desejado.</p></article></div></div></div></section>
    <section className="quote-section premium-quote" id="contato"><div className="container quote-layout"><div data-reveal><div className="section-index compact"><span>{sectionLabel(contactIndex)}</span><i/><small>CONTATO</small></div><div className="eyebrow">Orçamento personalizado</div><h2 className="section-title">Conte o que<br/><em>vamos criar.</em></h2><p className="muted">Se você ainda não escolheu peças do catálogo, envie uma ideia livre. A solicitação fica registrada no painel e o atendimento segue pelo WhatsApp.</p></div><div data-reveal><QuoteForm categories={categories}/></div></div></section>
    <MerlinMobileDock whatsapp={settings.whatsapp_number}/>
    <section className="cta premium-cta"><div className="container"><div className="cta-box" data-reveal><div><div className="eyebrow">Atendimento direto</div><h2>Seu projeto pode<br/><em>começar agora.</em></h2><p>Envie a ideia, data do evento e quantidade para iniciar seu orçamento.</p></div>{wa&&<a className="btn btn-primary btn-luxury" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Abrir WhatsApp</a>}</div></div></section><Footer settings={settings}/></main>;
}
