import { hasRecentAdminReauthentication,isAdmin } from '@/lib/auth';
import { deleteCategory, logAdminAction, StaleWriteError, updateCategory, requireCriticalAuditIntent } from '@/lib/db';
import { categorySchema } from '@/lib/validation';
import { isUuid, readJsonBody, sameOriginRequest } from '@/lib/security';
import { serverFailure } from '@/lib/observability';
import { recordAdminSecurityEventWithAlert } from '@/lib/admin-security-alerts';
import { expectedUpdatedAtFromRequest,requireExpectedUpdatedAt } from '@/lib/concurrency';
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401});if(!sameOriginRequest(request))return Response.json({error:'Origem inválida.'},{status:403});const{id}=await params;if(!isUuid(id))return Response.json({error:'ID inválido.'},{status:400});try{const body=await readJsonBody(request,24_000);const expectedUpdatedAt=requireExpectedUpdatedAt(body.expected_updated_at);const parsed=categorySchema.safeParse(body);if(!parsed.success)return Response.json({error:'Dados da categoria inválidos.'},{status:400});const category=await updateCategory(id,parsed.data,expectedUpdatedAt);if(!category)return Response.json({error:'Categoria não encontrada.'},{status:404});await logAdminAction('update','category',id,`Categoria atualizada: ${category.name}`);return Response.json({category});}catch(e){if(e instanceof StaleWriteError)return Response.json({error:e.message},{status:409});const msg=(e instanceof Error?e.message:'').toLowerCase();if(msg.includes('unique')||msg.includes('duplicate'))return Response.json({error:'Nome ou slug já utilizado.'},{status:409});return await serverFailure('admin.categories.update',e);}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401});if(!sameOriginRequest(request))return Response.json({error:'Origem inválida.'},{status:403});const{id}=await params;if(!isUuid(id))return Response.json({error:'ID inválido.'},{status:400});try{const expectedUpdatedAt=expectedUpdatedAtFromRequest(request);if(!(await hasRecentAdminReauthentication()))return Response.json({error:'Confirme novamente sua identidade para excluir a categoria.',reauth_required:true},{status:428});await requireCriticalAuditIntent('delete_category','category',id,'Exclusão de categoria autorizada após step-up MFA.');const deleted=await deleteCategory(id,expectedUpdatedAt);if(!deleted)return Response.json({error:'Esta categoria não existe mais ou está em uso por produtos. Atualize a lista e confira antes de tentar novamente.'},{status:409});await logAdminAction('delete','category',id,'Categoria excluída.');await recordAdminSecurityEventWithAlert({eventType:'critical_action',severity:'warning',summary:`Categoria excluída (${id}).`});return Response.json({ok:true});}catch(e){if(e instanceof StaleWriteError)return Response.json({error:e.message},{status:409});return await serverFailure('admin.categories.delete',e);}}
