'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, ArrowUpRight, FolderOpen, LoaderCircle, RotateCcw, Search, X } from 'lucide-react';
import { fetchJson } from '@/lib/client';
import SafeImage from './SafeImage';
import { useDialogA11y } from './useDialogA11y';

type SearchProduct={id:string;slug:string;name:string;category:string;image_url:string};
type SearchCategory={id:string;slug:string;name:string;image_url:string|null};
type SearchResponse={products:SearchProduct[];categories:SearchCategory[]};

export default function GlobalSearch(){
  const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[products,setProducts]=useState<SearchProduct[]>([]),[categories,setCategories]=useState<SearchCategory[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const inputRef=useRef<HTMLInputElement>(null),dialogRef=useRef<HTMLElement>(null),seq=useRef(0);
  useDialogA11y(open,dialogRef,()=>setOpen(false));
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(true)}};const onOpen=()=>setOpen(true);window.addEventListener('keydown',onKey);window.addEventListener('marques:open-search',onOpen);return()=>{window.removeEventListener('keydown',onKey);window.removeEventListener('marques:open-search',onOpen);};},[]);
  useEffect(()=>{if(open)requestAnimationFrame(()=>inputRef.current?.focus())},[open]);
  async function runSearch(value:string,token:number){setLoading(true);setError('');try{const data=await fetchJson<SearchResponse>(`/api/search?q=${encodeURIComponent(value.trim())}`,{},8000);if(token!==seq.current)return;setProducts(data.products||[]);setCategories(data.categories||[]);}catch(e){if(token!==seq.current)return;setProducts([]);setCategories([]);setError(e instanceof Error?e.message:'Não foi possível realizar a busca.');}finally{if(token===seq.current)setLoading(false)}}
  useEffect(()=>{if(!open)return;const token=++seq.current;const timer=setTimeout(()=>runSearch(query,token),query.trim()?220:0);return()=>clearTimeout(timer);},[query,open]);
  const retry=()=>{const token=++seq.current;void runSearch(query,token)};
  return <><button type="button" className="nav-search" onClick={()=>setOpen(true)} aria-label="Buscar no catálogo"><Search size={17}/><span>Buscar</span><kbd>⌘K</kbd></button>{open&&<div className="search-overlay" onMouseDown={e=>{if(e.currentTarget===e.target)setOpen(false)}}><section ref={dialogRef} className="search-dialog" role="dialog" aria-modal="true" aria-labelledby="global-search-title" tabIndex={-1}><header><Search size={20}/><label className="sr-only" htmlFor="global-search-input" id="global-search-title">Buscar produtos e coleções</label><input id="global-search-input" ref={inputRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque por topo, caixa, tema ou coleção..." autoComplete="off"/><button type="button" className="icon-btn" onClick={()=>setOpen(false)} aria-label="Fechar busca"><X size={18}/></button></header><div className="search-dialog-body" aria-live="polite" aria-busy={loading}>{loading&&<div className="search-loading"><LoaderCircle className="spin" size={18}/> Buscando...</div>}{!loading&&error&&<div className="search-error" role="alert"><AlertTriangle size={27}/><strong>Não foi possível buscar agora.</strong><p>{error}</p><button type="button" className="btn" onClick={retry}><RotateCcw size={15}/> Tentar novamente</button></div>}{!loading&&!error&&<>{categories.length>0&&<div className="search-group"><span>COLEÇÕES</span>{categories.map(c=><Link prefetch={false} key={c.id} href={`/categorias/${c.slug}`} onClick={()=>setOpen(false)}><div className="search-thumb category-thumb">{c.image_url?<SafeImage src={c.image_url} alt="" loading="lazy" decoding="async" sizes="54px"/>:<FolderOpen size={18}/>}</div><div><strong>{c.name}</strong><small>Ver coleção</small></div><ArrowUpRight size={16}/></Link>)}</div>}{products.length>0&&<div className="search-group"><span>PRODUTOS</span>{products.map(p=><Link prefetch={false} key={p.id} href={`/catalogo/${p.slug}`} onClick={()=>setOpen(false)}><div className="search-thumb"><SafeImage src={p.image_url} alt="" loading="lazy" decoding="async" sizes="54px"/></div><div><strong>{p.name}</strong><small>{p.category}</small></div><ArrowUpRight size={16}/></Link>)}</div>}{!products.length&&!categories.length&&<div className="search-empty"><Search size={28}/><strong>{query?'Nenhum resultado encontrado.':'Encontre qualquer peça em segundos.'}</strong><p>{query?'Tente outro nome, tema ou categoria.':'Digite para pesquisar produtos e coleções do catálogo.'}</p></div>}{query.trim()&&<Link className="search-all-results" href={`/?q=${encodeURIComponent(query.trim())}#catalogo`} onClick={()=>setOpen(false)}>Ver todos os resultados no catálogo <ArrowUpRight size={16}/></Link>}</>}</div><footer><span>ESC para fechar</span><span>Busca em produtos e coleções</span></footer></section></div>}</>;
}
