import Link from 'next/link';
import { ArrowUpRight, Gift, PackageCheck, Sparkles, Users, WalletCards } from 'lucide-react';
import { formatCatalogMoney, starterCatalogProducts } from '@/lib/catalog-merchandising';

const bands=[
  {label:'Até R$ 150',description:'Para começar com pontos de destaque sem montar uma mesa inteira.',slugs:['topo-classico-personalizado','display-mesa-personalizado','topper-docinho-personalizado']},
  {label:'R$ 150–300',description:'Uma composição equilibrada para festa em casa ou mesa compacta.',slugs:['kit-mini-festa','topo-classico-personalizado','display-mesa-personalizado','caixinha-milk-premium']},
  {label:'R$ 300–500',description:'Mais peças e presença visual para uma composição premium.',slugs:['kit-premium-festa','topo-premium-camadas','caixinha-milk-premium','display-mesa-personalizado','topper-docinho-personalizado']},
];
function product(slug:string){return starterCatalogProducts.find(item=>item.slug===slug);}
export default function OrderDecisionGuide(){
  return <section className="order-decision-guide" aria-labelledby="order-decision-title"><div className="container"><div className="order-decision-head"><div><div className="eyebrow">Planejamento sem adivinhação</div><h2 id="order-decision-title">Escolha pelo que importa<br/><em>para a sua festa.</em></h2></div><p>Use faixa de investimento e número de convidados como ponto de partida. O orçamento final continua personalizado.</p></div><div className="order-decision-grid"><div className="order-decision-budget"><div className="order-decision-column-title"><WalletCards size={20}/><div><small>POR INVESTIMENTO</small><strong>Três caminhos para começar</strong></div></div>{bands.map(band=>{const items=band.slugs.map(product).filter(Boolean) as typeof starterCatalogProducts;const total=items.reduce((sum,item)=>sum+item.price_cents*Math.max(1,item.min_quantity),0);return <article key={band.label}><div><small>{band.label}</small><strong>A partir de {formatCatalogMoney(total)}</strong><p>{band.description}</p></div><ul>{items.map(item=><li key={item.slug}><Sparkles size={13}/>{item.name}</li>)}</ul><Link href={`/orcamento?faixa=${encodeURIComponent(band.label)}`}>Planejar nessa faixa <ArrowUpRight size={14}/></Link></article>;})}</div><div className="order-decision-guests"><div className="order-decision-column-title"><Users size={20}/><div><small>POR CONVIDADOS</small><strong>Quantidade com mais contexto</strong></div></div><div className="guest-guide-list"><article><span>ATÉ 20</span><div><strong>Festa compacta</strong><p>Priorize topo, display e poucas lembrancinhas coordenadas.</p></div><Gift size={19}/></article><article><span>20–50</span><div><strong>Composição equilibrada</strong><p>Caixas e lembrancinhas já podem acompanhar o número de convidados.</p></div><PackageCheck size={19}/></article><article><span>50+</span><div><strong>Planejamento por volume</strong><p>Informe convidados no orçamento para receber sugestões de quantidade sem perder o pedido mínimo.</p></div><Users size={19}/></article></div><div className="order-decision-actions"><Link className="btn btn-primary" href="/orcamento">Planejar meu orçamento</Link><Link className="btn" href="/monte-seu-kit">Montar kit completo</Link></div></div></div></div></section>;
}
