'use client';
import { useEffect, useId, useState } from 'react';
import { ArrowRight, CalendarDays, Check, PartyPopper, ShoppingBag, Sparkles, Users } from 'lucide-react';
import type { Category, Product } from '@/lib/db';
import { fetchJson } from '@/lib/client';
import { useQuoteList } from './QuoteListProvider';
import SafeImage from './SafeImage';

const occasions=['Aniversário infantil','Aniversário adulto','Chá / Revelação','Batizado','Casamento','Evento corporativo','Outro'];
const budgets=['Até R$ 150','R$ 150–300','R$ 300–500','R$ 500–800','Acima de R$ 800','Quero orientação'];
function todayLocal(){const d=new Date();const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;}
export default function PartyConcierge({categories,sectionIndex='04'}:{products?:Product[];categories:Category[];sectionIndex?:string}){
  const quote=useQuoteList();const uid=useId().replace(/:/g,'');const fid=(name:string)=>`${uid}-${name}`;const [step,setStep]=useState(1);const [occasion,setOccasion]=useState('');const [theme,setTheme]=useState('');const [name,setName]=useState('');const [age,setAge]=useState('');const [guests,setGuests]=useState('');const [eventDate,setEventDate]=useState('');const [budget,setBudget]=useState('');const [desired,setDesired]=useState<string[]>([]);const [recommended,setRecommended]=useState<Product[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{const value=new URLSearchParams(location.search).get('occasion');if(value&&occasions.includes(value)){setOccasion(value);setStep(2);}},[]);
  async function generate(){setLoading(true);setError('');try{const data=await fetchJson<{products:Product[]}>('/api/concierge',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({theme,categories:desired})});setRecommended(data.products);applyBrief();setStep(4);}catch(e){setError(e instanceof Error?e.message:'Não foi possível gerar a curadoria.');}finally{setLoading(false);}}
  function toggleCategory(name:string){setDesired(current=>current.includes(name)?current.filter(x=>x!==name):current.length>=12?current:[...current,name]);}
  function applyBrief(){quote.setBrief({occasion,theme,celebrant_name:name,celebrant_age:age,guest_count:guests?Math.max(1,Number(guests)):null,budget_range:budget,desired_categories:desired,source:'concierge',event_date:eventDate});}
  function addRecommended(){applyBrief();quote.addProducts(recommended);}
  return <section className="concierge-section" id="concierge"><div className="container"><div className="section-index" data-reveal><span>{sectionIndex}</span><i/><small>CONCIERGE</small></div><div className="concierge-shell" data-reveal><div className="concierge-intro"><div className="eyebrow">Curadoria guiada</div><h2>Não sabe por onde<br/><em>começar?</em></h2><p>Conte o básico da festa. O site usa o seu próprio catálogo para montar uma seleção inicial — sem compromisso e sem cadastro.</p><div className="concierge-steps" aria-label="Etapas"><span className={step>=1?'active':''}>01 Ocasião</span><span className={step>=2?'active':''}>02 Evento</span><span className={step>=3?'active':''}>03 Peças</span><span className={step>=4?'active':''}>04 Curadoria</span></div></div><div className="concierge-panel">
      {step===1&&<div className="concierge-step"><small>ETAPA 01 / 04</small><h3>Qual é a ocasião?</h3><div className="concierge-options">{occasions.map(item=><button type="button" className={occasion===item?'active':''} onClick={()=>setOccasion(item)} key={item}><PartyPopper size={17}/>{item}{occasion===item&&<Check size={15}/>}</button>)}</div><button type="button" className="btn btn-primary concierge-next" disabled={!occasion} onClick={()=>setStep(2)}>Continuar <ArrowRight size={16}/></button></div>}
      {step===2&&<div className="concierge-step"><small>ETAPA 02 / 04</small><h3>Conte o essencial.</h3><div className="quote-brief-grid"><div className="field"><label htmlFor={fid('theme')}>Tema</label><input id={fid('theme')} placeholder="Ex.: Harry Potter" value={theme} onChange={e=>setTheme(e.target.value)}/></div><div className="field"><label htmlFor={fid('name')}>Nome</label><input id={fid('name')} placeholder="Quem será homenageado?" value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label htmlFor={fid('age')}>Idade</label><input id={fid('age')} inputMode="numeric" placeholder="Ex.: 29 anos" value={age} onChange={e=>setAge(e.target.value)}/></div><div className="field"><label htmlFor={fid('guests')}><Users size={14}/> Convidados</label><input id={fid('guests')} type="number" min="1" max="10000" placeholder="Ex.: 40" value={guests} onChange={e=>setGuests(e.target.value)}/></div><div className="field"><label htmlFor={fid('event-date')}><CalendarDays size={14}/> Data do evento</label><input id={fid('event-date')} type="date" min={todayLocal()} value={eventDate} onChange={e=>setEventDate(e.target.value)}/></div><div className="field"><label htmlFor={fid('budget')}>Faixa de investimento</label><select id={fid('budget')} value={budget} onChange={e=>setBudget(e.target.value)}><option value="">Ainda não sei</option>{budgets.map(item=><option key={item}>{item}</option>)}</select></div></div><div className="concierge-navigation"><button type="button" className="btn" onClick={()=>setStep(1)}>Voltar</button><button type="button" className="btn btn-primary" onClick={()=>setStep(3)}>Continuar <ArrowRight size={16}/></button></div></div>}
      {step===3&&<div className="concierge-step"><small>ETAPA 03 / 04</small><h3>Quais peças você imagina?</h3><p className="muted">Pode marcar várias. Se deixar tudo em branco, o Concierge considera o catálogo inteiro.</p><div className="concierge-category-grid">{categories.map(category=><button type="button" className={desired.includes(category.name)?'active':''} onClick={()=>toggleCategory(category.name)} key={category.id}><span>{category.name}</span>{desired.includes(category.name)?<Check size={16}/>:<Sparkles size={16}/>}</button>)}</div>{error&&<div className="error" role="alert">{error}</div>}<div className="concierge-navigation"><button type="button" className="btn" onClick={()=>setStep(2)}>Voltar</button><button type="button" className="btn btn-primary" disabled={loading} onClick={generate}>{loading?'Gerando…':'Gerar curadoria'} <Sparkles size={16}/></button></div></div>}
      {step===4&&<div className="concierge-step concierge-result"><small>CURADORIA INICIAL</small><h3>{theme?`Uma seleção para “${theme}”.`:'Uma seleção para começar.'}</h3><p className="muted">Você pode adicionar tudo à lista e ajustar quantidades antes de enviar o orçamento.</p><div className="concierge-products">{recommended.map((product,index)=><a href={`/catalogo/${product.slug}`} key={product.id}><div><SafeImage src={product.image_urls[0]} alt={product.name} loading="lazy" decoding="async"/></div><span>{String(index+1).padStart(2,'0')} • {product.category}</span><strong>{product.name}</strong></a>)}{!recommended.length&&<div className="empty">Não há peças publicadas para essa combinação ainda.</div>}</div><div className="concierge-navigation"><button type="button" className="btn" onClick={()=>setStep(3)}>Ajustar escolhas</button>{recommended.length>0&&<button type="button" className="btn btn-primary" onClick={addRecommended}><ShoppingBag size={16}/> Adicionar seleção à minha lista</button>}</div>{eventDate&&<small className="concierge-date-note">Data informada: {eventDate.split('-').reverse().join('/')} — ela será mantida quando você finalizar o orçamento.</small>}</div>}
    </div></div></div></section>;
}
