'use client';
import { useEffect, useId, useState } from 'react';
import { ArrowRight, ArrowUpRight, CalendarDays, Check, MessageCircle, PartyPopper, ShoppingBag, Sparkles, Users } from 'lucide-react';
import type { Category, Product } from '@/lib/db';
import type { InspirationModel } from '@/lib/inspirations';
import { recommendInspirations } from '@/lib/inspirations';
import { whatsappUrl } from '@/lib/links';
import { fetchJson } from '@/lib/client';
import { useQuoteList } from './QuoteListProvider';
import SafeImage from './SafeImage';

const occasions=['Aniversário infantil','1º aniversário','Aniversário adulto','15 anos','Chá de bebê / Revelação','Batizado','Casamento / Noivado','Formatura','Evento corporativo','Outro'];
const budgets=['Até R$ 150','R$ 150–300','R$ 300–500','R$ 500–800','Acima de R$ 800','Quero orientação'];
function todayLocal(){const d=new Date();const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;}

export default function PartyConcierge({categories,whatsapp='',sectionIndex='04'}:{products?:Product[];categories:Category[];whatsapp?:string;sectionIndex?:string}){
  const quote=useQuoteList();const uid=useId().replace(/:/g,'');const fid=(name:string)=>`${uid}-${name}`;
  const [step,setStep]=useState(1);const [occasion,setOccasion]=useState('');const [theme,setTheme]=useState('');const [name,setName]=useState('');const [age,setAge]=useState('');const [guests,setGuests]=useState('');const [eventDate,setEventDate]=useState('');const [budget,setBudget]=useState('');const [desired,setDesired]=useState<string[]>([]);const [recommended,setRecommended]=useState<Product[]>([]);const [inspirationFallback,setInspirationFallback]=useState<InspirationModel[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{const params=new URLSearchParams(location.search);const occasionParam=params.get('occasion')||'';const themeParam=params.get('theme')||'';const budgetParam=params.get('budget')||'';if(occasionParam){setOccasion(occasionParam);setStep(2);}if(themeParam)setTheme(themeParam);if(budgetParam){const match=budgets.find(item=>item.toLocaleLowerCase('pt-BR').includes(budgetParam.toLocaleLowerCase('pt-BR'))||item.replace(/\s/g,'').includes(budgetParam.replace(/\s/g,'')));if(match)setBudget(match);}},[]);
  function applyBrief(){quote.setBrief({occasion,theme,celebrant_name:name,celebrant_age:age,guest_count:guests?Math.max(1,Number(guests)):null,budget_range:budget,desired_categories:desired,source:'concierge',event_date:eventDate});}
  async function generate(){setLoading(true);setError('');try{const data=await fetchJson<{products:Product[]}>('/api/concierge',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({theme,categories:desired})});setRecommended(data.products);setInspirationFallback(data.products.length?[]:recommendInspirations({theme,occasion,budget,categories:desired},6));applyBrief();setStep(4);}catch(e){const fallback=recommendInspirations({theme,occasion,budget,categories:desired},6);if(fallback.length){setRecommended([]);setInspirationFallback(fallback);applyBrief();setStep(4);setError('');}else setError(e instanceof Error?e.message:'Não foi possível gerar a curadoria.');}finally{setLoading(false);}}
  function toggleCategory(categoryName:string){setDesired(current=>current.includes(categoryName)?current.filter(x=>x!==categoryName):current.length>=12?current:[...current,categoryName]);}
  function addRecommended(){applyBrief();quote.addProducts(recommended);}
  function inspirationWhatsapp(model:InspirationModel){return whatsappUrl(whatsapp,`Olá! Montei minha festa no site da Merlin Encantos em Papel e gostei da inspiração ${model.code} — ${model.title}. Ocasião: ${occasion||'a definir'}. Tema: ${theme||'a definir'}. Convidados: ${guests||'a definir'}. Faixa: ${budget||'a definir'}. Quero um orçamento nesse estilo.`);}
  const generalWa=whatsappUrl(whatsapp,`Olá! Usei o Monte sua Festa da Merlin Encantos em Papel. Ocasião: ${occasion||'a definir'}. Tema: ${theme||'a definir'}. Nome: ${name||'a definir'}. Idade: ${age||'a definir'}. Convidados: ${guests||'a definir'}. Data: ${eventDate||'a definir'}. Faixa: ${budget||'a definir'}. Quero ajuda para montar meu pedido.`);
  return <section className="concierge-section" id="concierge"><div className="container"><div className="section-index" data-reveal><span>{sectionIndex}</span><i/><small>MONTE SUA FESTA</small></div><div className="concierge-shell" data-reveal><div className="concierge-intro"><div className="eyebrow">Curadoria guiada</div><h2>Conte sobre a festa.<br/><em>A gente organiza as ideias.</em></h2><p>Você informa ocasião, tema, convidados e faixa de investimento. O site procura primeiro no catálogo publicado e, enquanto ele cresce, também sugere modelos de inspiração da Merlin.</p><div className="concierge-steps" aria-label="Etapas"><span className={step>=1?'active':''}>01 Ocasião</span><span className={step>=2?'active':''}>02 Evento</span><span className={step>=3?'active':''}>03 Peças</span><span className={step>=4?'active':''}>04 Curadoria</span></div></div><div className="concierge-panel">
    {step===1&&<div className="concierge-step"><small>ETAPA 01 / 04</small><h3>Qual é a ocasião?</h3><div className="concierge-options">{occasions.map(item=><button type="button" className={occasion===item?'active':''} onClick={()=>setOccasion(item)} key={item}><PartyPopper size={17}/>{item}{occasion===item&&<Check size={15}/>}</button>)}</div><button type="button" className="btn btn-primary concierge-next" disabled={!occasion} onClick={()=>setStep(2)}>Continuar <ArrowRight size={16}/></button></div>}
    {step===2&&<div className="concierge-step"><small>ETAPA 02 / 04</small><h3>Conte o essencial.</h3><div className="quote-brief-grid"><div className="field"><label htmlFor={fid('theme')}>Tema ou referência</label><input id={fid('theme')} placeholder="Ex.: floral rosé, gamer, Harry Potter..." value={theme} onChange={e=>setTheme(e.target.value)}/></div><div className="field"><label htmlFor={fid('name')}>Nome</label><input id={fid('name')} placeholder="Quem será homenageado?" value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label htmlFor={fid('age')}>Idade</label><input id={fid('age')} inputMode="numeric" placeholder="Ex.: 29 anos" value={age} onChange={e=>setAge(e.target.value)}/></div><div className="field"><label htmlFor={fid('guests')}><Users size={14}/> Convidados</label><input id={fid('guests')} type="number" min="1" max="10000" placeholder="Ex.: 40" value={guests} onChange={e=>setGuests(e.target.value)}/></div><div className="field"><label htmlFor={fid('event-date')}><CalendarDays size={14}/> Data do evento</label><input id={fid('event-date')} type="date" min={todayLocal()} value={eventDate} onChange={e=>setEventDate(e.target.value)}/></div><div className="field"><label htmlFor={fid('budget')}>Faixa de investimento</label><select id={fid('budget')} value={budget} onChange={e=>setBudget(e.target.value)}><option value="">Ainda não sei</option>{budgets.map(item=><option key={item}>{item}</option>)}</select></div></div><div className="concierge-navigation"><button type="button" className="btn" onClick={()=>setStep(1)}>Voltar</button><button type="button" className="btn btn-primary" onClick={()=>setStep(3)}>Continuar <ArrowRight size={16}/></button></div></div>}
    {step===3&&<div className="concierge-step"><small>ETAPA 03 / 04</small><h3>Quais peças você imagina?</h3><p className="muted">Pode marcar várias. Se deixar tudo em branco, a curadoria considera todas as possibilidades.</p><div className="concierge-category-grid">{categories.map(category=><button type="button" className={desired.includes(category.name)?'active':''} onClick={()=>toggleCategory(category.name)} key={category.id}><span>{category.name}</span>{desired.includes(category.name)?<Check size={16}/>:<Sparkles size={16}/>}</button>)}</div>{error&&<div className="error" role="alert">{error}</div>}<div className="concierge-navigation"><button type="button" className="btn" onClick={()=>setStep(2)}>Voltar</button><button type="button" className="btn btn-primary" disabled={loading} onClick={generate}>{loading?'Gerando…':'Montar sugestões'} <Sparkles size={16}/></button></div></div>}
    {step===4&&<div className="concierge-step concierge-result"><small>CURADORIA INICIAL</small><h3>{theme?`Ideias para “${theme}”.`:'Uma seleção para começar.'}</h3>{recommended.length>0?<><p className="muted">Encontramos peças publicadas no catálogo. Adicione a seleção à sua lista e ajuste as quantidades antes de enviar o orçamento.</p><div className="concierge-products">{recommended.map((product,index)=><a href={`/catalogo/${product.slug}`} key={product.id}><div><SafeImage src={product.image_urls[0]} alt={product.name} loading="lazy" decoding="async"/></div><span>{String(index+1).padStart(2,'0')} • {product.category}</span><strong>{product.name}</strong></a>)}</div></>:<><p className="muted">O catálogo de produtos produzidos ainda está crescendo, então separamos modelos de inspiração coerentes com o seu briefing. Eles funcionam como ponto de partida para o orçamento.</p><div className="concierge-inspiration-grid">{inspirationFallback.map(model=><article key={model.code}><div className={`concierge-inspiration-art palette-${model.palette}`}><span>{model.code}</span><strong>{model.title.slice(0,2).toUpperCase()}</strong></div><div><small>{model.category} • {model.tier}</small><h4>{model.title}</h4><p>{model.description}</p>{inspirationWhatsapp(model)&&<a href={inspirationWhatsapp(model)} target="_blank" rel="noreferrer"><MessageCircle size={14}/> Quero esse estilo</a>}</div></article>)}</div></>}
      <div className="concierge-navigation"><button type="button" className="btn" onClick={()=>setStep(3)}>Ajustar escolhas</button>{recommended.length>0&&<button type="button" className="btn btn-primary" onClick={addRecommended}><ShoppingBag size={16}/> Adicionar seleção à minha lista</button>}{generalWa&&<a className="btn btn-primary" href={generalWa} target="_blank" rel="noreferrer"><MessageCircle size={16}/> Pedir ajuda no WhatsApp</a>}<a className="btn" href="/inspiracoes#explorar-inspiracoes">Ver catálogo de ideias <ArrowUpRight size={15}/></a></div>{eventDate&&<small className="concierge-date-note">Data informada: {eventDate.split('-').reverse().join('/')} — ela será mantida quando você finalizar o orçamento.</small>}</div>}
  </div></div></div></section>;
}
