'use client';
import Link from 'next/link';
import { useEffect, useId, useRef, useState } from 'react';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import type { Category, Product } from '@/lib/db';
import { fetchJson } from '@/lib/client';
import { getAttribution } from '@/lib/attribution-client';
import ProductCustomizationFields from './ProductCustomizationFields';
const occasions=['Aniversário infantil','Aniversário adulto','Chá / Revelação','Batizado','Casamento','Evento corporativo','Outro'];
const budgets=['Até R$ 150','R$ 150–300','R$ 300–500','R$ 500–800','Acima de R$ 800','Quero orientação'];
function todayLocal(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function makeRequestId(){if(globalThis.crypto?.randomUUID)return globalThis.crypto.randomUUID();const b=new Uint8Array(16);globalThis.crypto.getRandomValues(b);b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
type InquiryResponse={ok:boolean;id?:string;persisted?:boolean;contingency?:boolean;whatsapp_url?:string};
export default function QuoteForm({categories,product,compact=false}:{categories:Category[];product?:Product;compact?:boolean}){
  const uid=useId().replace(/:/g,'');const fid=(name:string)=>`${uid}-${name}`;
  const [form,setForm]=useState({name:'',whatsapp:'',email:'',event_date:'',category:product?.category||'',message:product?`Gostaria de um orçamento e opções de personalização para ${product.name}.`:'',website:'',occasion:'',theme:'',celebrant_name:'',celebrant_age:'',guest_count:'',budget_range:''});
  const requestId=useRef(makeRequestId());const errorRef=useRef<HTMLDivElement>(null);
  const [customizations,setCustomizations]=useState<Record<string,string>>({});
  const [loading,setLoading]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[persisted,setPersisted]=useState(true),[whatsappOpened,setWhatsappOpened]=useState(false);
  useEffect(()=>{if(error)requestAnimationFrame(()=>errorRef.current?.focus());},[error]);
  function set(k:keyof typeof form,v:string){setForm(p=>({...p,[k]:v}));}
  async function submit(e:React.FormEvent){e.preventDefault();if(loading)return;setLoading(true);setError('');const {occasion,theme,celebrant_name,celebrant_age,guest_count,budget_range,...base}=form;const brief={occasion,theme,celebrant_name,celebrant_age,guest_count:guest_count?Math.max(1,Number(guest_count)):null,budget_range,desired_categories:form.category?[form.category]:[],source:'site' as const,attribution:getAttribution()};try{if(product){for(const field of product.customization_fields||[]){if(field.required&&!String(customizations[field.id]||'').trim()){setError(`Preencha “${field.label}”.`);setLoading(false);return;}}}const items=product?[{product_id:product.id,quantity:Math.max(1,product.min_quantity||1),customizations}]:[];const data=await fetchJson<InquiryResponse>('/api/inquiries',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...base,request_id:requestId.current,brief,items,product_id:'',product_name:''})},18000);setDone(true);setPersisted(data.persisted!==false);setWhatsappOpened(Boolean(data.whatsapp_url));if(data.whatsapp_url)window.location.assign(data.whatsapp_url);}catch(e){setError(e instanceof Error?e.message:'Não foi possível enviar o orçamento.');}finally{setLoading(false);}}
  if(done)return <div className="quote-success" role="status" aria-live="polite"><CheckCircle2 size={28}/><div><strong>{persisted?'Solicitação registrada.':'Atendimento em contingência.'}</strong><p>{persisted?(whatsappOpened?'Seu orçamento ficou salvo. O WhatsApp será aberto para continuar o atendimento.':'Seu orçamento ficou salvo. O atendimento poderá continuar pelos dados informados.'):'O registro automático está temporariamente indisponível. Seus dados continuam preenchidos nesta página e o WhatsApp será aberto para você continuar sem perder o atendimento.'}</p></div></div>;
  return <form className={`quote-form ${compact?'compact':''}`} onSubmit={submit} aria-describedby={error?fid('error'):undefined}><div className="quote-form-grid">
    <div className="field"><label htmlFor={fid('name')}>Seu nome</label><input id={fid('name')} autoComplete="name" minLength={2} maxLength={120} value={form.name} onChange={e=>set('name',e.target.value)} required/></div>
    <div className="field"><label htmlFor={fid('whatsapp')}>WhatsApp</label><input id={fid('whatsapp')} inputMode="tel" autoComplete="tel" minLength={8} maxLength={30} placeholder="(98) 99999-9999" value={form.whatsapp} onChange={e=>set('whatsapp',e.target.value)} required/></div>
    <div className="field"><label htmlFor={fid('email')}>E-mail (opcional)</label><input id={fid('email')} type="email" autoComplete="email" maxLength={180} value={form.email} onChange={e=>set('email',e.target.value)}/></div>
    <div className="field"><label htmlFor={fid('date')}>Data do evento</label><input id={fid('date')} type="date" min={todayLocal()} value={form.event_date} onChange={e=>set('event_date',e.target.value)}/></div>
    <div className="field"><label htmlFor={fid('occasion')}>Ocasião</label><select id={fid('occasion')} value={form.occasion} onChange={e=>set('occasion',e.target.value)}><option value="">Selecione</option>{occasions.map(x=><option key={x}>{x}</option>)}</select></div>
    <div className="field"><label htmlFor={fid('theme')}>Tema</label><input id={fid('theme')} maxLength={120} placeholder="Ex.: Harry Potter" value={form.theme} onChange={e=>set('theme',e.target.value)}/></div>
    <div className="field"><label htmlFor={fid('celebrant')}>Nome / homenageado</label><input id={fid('celebrant')} maxLength={120} value={form.celebrant_name} onChange={e=>set('celebrant_name',e.target.value)}/></div>
    <div className="field"><label htmlFor={fid('age')}>Idade</label><input id={fid('age')} maxLength={40} placeholder="Ex.: 29 anos" value={form.celebrant_age} onChange={e=>set('celebrant_age',e.target.value)}/></div>
    <div className="field"><label htmlFor={fid('guests')}>Convidados</label><input id={fid('guests')} type="number" min="1" max="10000" placeholder="Ex.: 40" value={form.guest_count} onChange={e=>set('guest_count',e.target.value)}/></div>
    <div className="field"><label htmlFor={fid('budget')}>Faixa de investimento</label><select id={fid('budget')} value={form.budget_range} onChange={e=>set('budget_range',e.target.value)}><option value="">Não definido</option>{budgets.map(x=><option key={x}>{x}</option>)}</select></div>
    {product&&product.customization_fields.length>0&&<div className="quote-span quote-product-customization"><div className="eyebrow">Detalhes desta peça</div><ProductCustomizationFields fields={product.customization_fields} values={customizations} onChange={(id,value)=>setCustomizations(current=>({...current,[id]:value}))} disabled={loading}/></div>}
    {!product&&<div className="field quote-span"><label htmlFor={fid('category')}>O que você procura?</label><select id={fid('category')} value={form.category} onChange={e=>set('category',e.target.value)}><option value="">Selecione ou deixe em aberto</option>{categories.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></div>}
    <div className="field quote-span"><label htmlFor={fid('message')}>Conte o que você precisa</label><textarea id={fid('message')} maxLength={2000} placeholder="Quantidade, cores, acabamento, referências e qualquer detalhe importante..." value={form.message} onChange={e=>set('message',e.target.value)} required/></div>
    <input className="hp-field" tabIndex={-1} autoComplete="off" aria-hidden="true" value={form.website} onChange={e=>set('website',e.target.value)}/>
  </div>{error&&<div ref={errorRef} id={fid('error')} className="error" role="alert" tabIndex={-1}>{error}</div>}<button type="submit" className="btn btn-primary" disabled={loading} aria-busy={loading}>{loading?'Enviando...':'Solicitar orçamento'}<ArrowRight size={17}/></button><small className="form-note">Ao enviar, sua solicitação fica registrada para atendimento. Se o WhatsApp oficial estiver configurado, você será direcionado para continuar a conversa. <Link href="/privacidade">Privacidade</Link>.</small></form>;
}
