'use client';
import Link from 'next/link';
import { useEffect } from 'react';
import { AlertTriangle, ArrowRight, CalendarDays, Check, CheckCircle2, Circle, Clock3, Minus, Plus, ShoppingBag, Sparkles, Trash2, Users, WalletCards } from 'lucide-react';
import { evaluateBudget, evaluateDeadline, estimateQuote, moneyBRL, quoteReadiness } from '@/lib/quote-planning';
import { useQuoteList } from './QuoteListProvider';
import SafeImage from './SafeImage';

const occasions=['Aniversário infantil','Aniversário adulto','Chá / Revelação','Batizado','Casamento','Evento corporativo','Outro'];
const budgets=['Até R$ 150','R$ 150–300','R$ 300–500','R$ 500–800','Acima de R$ 800','Quero orientação'];
function todayLocal(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}

export default function QuoteWorkspace(){
  const quote=useQuoteList();
  useEffect(()=>{const params=new URLSearchParams(location.search);const faixa=params.get('faixa');const convidados=params.get('convidados');if(faixa||convidados)quote.setBrief({budget_range:faixa||quote.brief.budget_range||'',guest_count:convidados?Math.max(1,Number(convidados)||1):quote.brief.guest_count||null});},[]);
  const estimate=estimateQuote(quote.items);
  const budget=evaluateBudget(estimate.totalCents,quote.brief.budget_range);
  const deadline=evaluateDeadline(quote.items,quote.brief.event_date);
  const readiness=quoteReadiness({itemCount:quote.items.length,occasion:quote.brief.occasion,theme:quote.brief.theme,eventDate:quote.brief.event_date,guestCount:quote.brief.guest_count,budgetRange:quote.brief.budget_range});
  if(!quote.items.length)return <section className="quote-workspace-empty"><ShoppingBag size={40}/><div className="eyebrow">ORÇAMENTO MERLIN</div><h1>Sua seleção ainda está vazia.</h1><p>Explore o catálogo, escolha as peças e volte aqui para revisar quantidades, valor inicial, briefing e prazo.</p><div><Link className="btn btn-primary" href="/#catalogo">Explorar catálogo</Link><Link className="btn" href="/monte-seu-kit">Montar um kit</Link></div></section>;
  return <div className="quote-workspace">
    <section className="quote-workspace-hero"><div><div className="eyebrow">PLANEJADOR DE ORÇAMENTO</div><h1>Revise o pedido<br/><em>antes de enviar.</em></h1><p>Organize quantidades e briefing em uma única tela. Os valores são estimativas mínimas com base no catálogo atual.</p></div><div className="quote-workspace-score"><span>BRIEFING</span><strong>{readiness.percent}%</strong><div><i style={{width:`${readiness.percent}%`}}/></div><small>{readiness.done} de {readiness.total} informações essenciais preenchidas</small></div></section>
    <div className="quote-workspace-grid"><div className="quote-workspace-main">
      <section className="quote-workspace-card"><div className="quote-workspace-card-head"><div><small>01 • PEÇAS</small><h2>Produtos e quantidades</h2></div><span>{quote.items.length} {quote.items.length===1?'item':'itens'}</span></div><div className="quote-workspace-items">{quote.items.map(item=><article key={item.product_id}><SafeImage src={item.image_url} alt="" loading="lazy" decoding="async"/><div className="quote-workspace-item-copy"><small>{item.category}</small><Link href={`/catalogo/${item.slug}`}>{item.name}</Link><span>{typeof item.price_cents==='number'?`${moneyBRL(item.price_cents)} por unidade`:'Valor sob consulta'}</span></div><div className="quote-workspace-qty"><button type="button" onClick={()=>quote.setQuantity(item.product_id,item.quantity-1)} disabled={item.quantity<=item.min_quantity} aria-label={`Diminuir ${item.name}`}><Minus size={15}/></button><input inputMode="numeric" value={item.quantity} onChange={e=>quote.setQuantity(item.product_id,Number(e.target.value)||item.min_quantity)} aria-label={`Quantidade de ${item.name}`}/><button type="button" onClick={()=>quote.setQuantity(item.product_id,item.quantity+1)} aria-label={`Aumentar ${item.name}`}><Plus size={15}/></button></div><div className="quote-workspace-line-total"><small>A partir de</small><strong>{typeof item.price_cents==='number'?moneyBRL(item.price_cents*item.quantity):'—'}</strong></div><button className="quote-workspace-remove" type="button" onClick={()=>quote.removeProduct(item.product_id)} aria-label={`Remover ${item.name}`}><Trash2 size={16}/></button></article>)}</div><Link className="quote-workspace-add-more" href="/#catalogo"><Plus size={15}/> Adicionar mais produtos</Link></section>
      <section className="quote-workspace-card"><div className="quote-workspace-card-head"><div><small>02 • EVENTO</small><h2>Briefing essencial</h2></div><Sparkles size={20}/></div><div className="quote-workspace-form-grid"><label>Ocasião<select value={quote.brief.occasion||''} onChange={e=>quote.setBrief({occasion:e.target.value})}><option value="">Selecione</option>{occasions.map(item=><option key={item}>{item}</option>)}</select></label><label>Tema ou referência<input maxLength={120} placeholder="Ex.: floral rosé, Stitch, futebol..." value={quote.brief.theme||''} onChange={e=>quote.setBrief({theme:e.target.value})}/></label><label>Nome / homenageado<input maxLength={120} value={quote.brief.celebrant_name||''} onChange={e=>quote.setBrief({celebrant_name:e.target.value})}/></label><label>Idade<input maxLength={40} placeholder="Ex.: 5 anos" value={quote.brief.celebrant_age||''} onChange={e=>quote.setBrief({celebrant_age:e.target.value})}/></label><label><Users size={14}/> Convidados<input type="number" min="1" max="10000" placeholder="Ex.: 40" value={quote.brief.guest_count||''} onChange={e=>quote.setBrief({guest_count:e.target.value?Math.max(1,Number(e.target.value)):null})}/></label><label><WalletCards size={14}/> Faixa de investimento<select value={quote.brief.budget_range||''} onChange={e=>quote.setBrief({budget_range:e.target.value})}><option value="">Ainda não defini</option>{budgets.map(item=><option key={item}>{item}</option>)}</select></label><label className="quote-workspace-date"><CalendarDays size={14}/> Data do evento<input type="date" min={todayLocal()} value={quote.brief.event_date||''} onChange={e=>quote.setBrief({event_date:e.target.value})}/></label></div></section>
      <section className="quote-workspace-card quote-readiness"><div className="quote-workspace-card-head"><div><small>03 • CONFERÊNCIA</small><h2>Seu pedido está pronto para atendimento?</h2></div><strong>{readiness.percent}%</strong></div><div className="quote-readiness-grid">{readiness.checks.map(item=><div className={item.done?'done':''} key={item.key}>{item.done?<CheckCircle2 size={18}/>:<Circle size={18}/>}<span>{item.label}</span></div>)}</div></section>
    </div><aside className="quote-workspace-aside">
      <section className="quote-workspace-summary"><small>ESTIMATIVA INICIAL</small><strong>{estimate.pricedCount?moneyBRL(estimate.totalCents):'Sob consulta'}</strong><p>{estimate.complete?'Todos os itens da seleção possuem preço inicial.':'Há itens sem preço inicial; o valor exibido considera apenas os produtos precificados.'}</p><div className={`quote-health status-${budget.state}`}><WalletCards size={18}/><div><strong>{budget.label}</strong><span>{budget.detail}</span></div></div><div className={`quote-health status-${deadline.state}`}><Clock3 size={18}/><div><strong>{deadline.label}</strong><span>{deadline.detail}</span></div></div><div className="quote-workspace-disclaimer"><AlertTriangle size={16}/><span>Estimativa não é preço final. Personalização, acabamento, disponibilidade de agenda, urgência e frete são confirmados no atendimento.</span></div><button className="btn btn-primary quote-workspace-submit" type="button" onClick={()=>quote.setOpen(true)}>Continuar para envio <ArrowRight size={17}/></button><Link className="quote-workspace-secondary" href="/guia-de-precos">Consultar guia de preços</Link></section>
    </aside></div>
  </div>;
}
