import crypto from 'node:crypto';

export const BACKUP_ENCRYPTION_CONTRACT='marques-backup-encrypted-v1';
export type BackupEncryptionStatus={status:'encrypted'|'plaintext';key_source:'current'|'previous'|null;key_id:string|null};
export type DecryptedBackup={plaintext:string;encryption:BackupEncryptionStatus};

type Envelope={version:number;backup_envelope:string;created_at:string;cipher:string;kdf:string;key_id:string;salt:string;iv:string;auth_tag:string;ciphertext:string};
function config(){return{current:String(process.env.BACKUP_ENCRYPTION_SECRET||'').trim(),previous:String(process.env.BACKUP_ENCRYPTION_PREVIOUS_SECRET||'').trim(),keyId:(String(process.env.BACKUP_ENCRYPTION_KEY_ID||'primary').trim().slice(0,64)||'primary')};}
function b64url(buffer:Buffer){return buffer.toString('base64url');}
function fromB64url(value:string){if(!/^[A-Za-z0-9_-]+$/.test(value))throw new Error('BACKUP_ENVELOPE_INVALID');return Buffer.from(value,'base64url');}
function aadFor(row:{version:number;backup_envelope:string;created_at:string;key_id:string}){return Buffer.from(JSON.stringify({contract:BACKUP_ENCRYPTION_CONTRACT,version:Number(row.version),backup_envelope:String(row.backup_envelope),created_at:String(row.created_at),key_id:String(row.key_id)}),'utf8');}
function key(secret:string,salt:Buffer){return Buffer.from(crypto.hkdfSync('sha256',Buffer.from(secret,'utf8'),salt,Buffer.from(BACKUP_ENCRYPTION_CONTRACT,'utf8'),32));}
function validSecret(secret:string){return secret.length>=32;}
function parseEnvelope(raw:string):Envelope|null{let parsed:unknown;try{parsed=JSON.parse(raw);}catch{return null;}if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))return null;const row=parsed as Record<string,unknown>;if(row.backup_envelope!==BACKUP_ENCRYPTION_CONTRACT)return null;const envelope={version:Number(row.version),backup_envelope:String(row.backup_envelope),created_at:String(row.created_at||''),cipher:String(row.cipher||''),kdf:String(row.kdf||''),key_id:String(row.key_id||''),salt:String(row.salt||''),iv:String(row.iv||''),auth_tag:String(row.auth_tag||''),ciphertext:String(row.ciphertext||'')};if(envelope.version!==1||envelope.cipher!=='aes-256-gcm'||envelope.kdf!=='hkdf-sha256'||!envelope.created_at||!envelope.key_id||!envelope.salt||!envelope.iv||!envelope.auth_tag||!envelope.ciphertext)throw new Error('BACKUP_ENVELOPE_INVALID');return envelope;}
function decryptWith(secret:string,envelope:Envelope){const salt=fromB64url(envelope.salt),iv=fromB64url(envelope.iv),tag=fromB64url(envelope.auth_tag),ciphertext=fromB64url(envelope.ciphertext);if(salt.length!==16||iv.length!==12||tag.length!==16)throw new Error('BACKUP_ENVELOPE_INVALID');const decipher=crypto.createDecipheriv('aes-256-gcm',key(secret,salt),iv);decipher.setAAD(aadFor(envelope));decipher.setAuthTag(tag);return Buffer.concat([decipher.update(ciphertext),decipher.final()]).toString('utf8');}
export function encryptBackupText(plaintext:string){const {current,keyId}=config();if(!validSecret(current))throw new Error('BACKUP_ENCRYPTION_SECRET_MISSING');const salt=crypto.randomBytes(16),iv=crypto.randomBytes(12),createdAt=new Date().toISOString();const base={version:1,backup_envelope:BACKUP_ENCRYPTION_CONTRACT,created_at:createdAt,key_id:keyId};const cipher=crypto.createCipheriv('aes-256-gcm',key(current,salt),iv);cipher.setAAD(aadFor(base));const ciphertext=Buffer.concat([cipher.update(Buffer.from(plaintext,'utf8')),cipher.final()]);const envelope:Envelope={...base,cipher:'aes-256-gcm',kdf:'hkdf-sha256',salt:b64url(salt),iv:b64url(iv),auth_tag:b64url(cipher.getAuthTag()),ciphertext:b64url(ciphertext)};return JSON.stringify(envelope,null,2);}
export function decryptBackupText(raw:string,options:{requireEncryption?:boolean}={}):DecryptedBackup{const envelope=parseEnvelope(raw);if(!envelope){if(options.requireEncryption)throw new Error('BACKUP_ENCRYPTION_REQUIRED');return{plaintext:raw,encryption:{status:'plaintext',key_source:null,key_id:null}};}const {current,previous}=config();if(!validSecret(current)&&!validSecret(previous))throw new Error('BACKUP_ENCRYPTION_SECRET_MISSING');if(validSecret(current)){try{return{plaintext:decryptWith(current,envelope),encryption:{status:'encrypted',key_source:'current',key_id:envelope.key_id}};}catch(error){if(error instanceof Error&&error.message==='BACKUP_ENVELOPE_INVALID')throw error;}}
if(validSecret(previous)){try{return{plaintext:decryptWith(previous,envelope),encryption:{status:'encrypted',key_source:'previous',key_id:envelope.key_id}};}catch(error){if(error instanceof Error&&error.message==='BACKUP_ENVELOPE_INVALID')throw error;}}
throw new Error('BACKUP_DECRYPTION_FAILED');}
