import { hasRecentAdminReauthentication,isAdmin } from '@/lib/auth';
import { CampaignHasLeadsError,CampaignSlugImmutableError,deleteMarketingCampaign,logAdminAction,StaleWriteError,updateMarketingCampaign, requireCriticalAuditIntent } from '@/lib/db';
import { serverFailure } from '@/lib/observability';
import { isUuid,readJsonBody,sameOriginRequest } from '@/lib/security';
import { marketingCampaignSchema } from '@/lib/validation';
import { recordAdminSecurityEventWithAlert } from '@/lib/admin-security-alerts';
import { expectedUpdatedAtFromRequest,requireExpectedUpdatedAt } from '@/lib/concurrency';
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401});if(!sameOriginRequest(request))return Response.json({error:'Origem inválida.'},{status:403});const{id}=await params;if(!isUuid(id))return Response.json({error:'ID inválido.'},{status:400});try{const body=await readJsonBody(request,18_000);const expectedUpdatedAt=requireExpectedUpdatedAt(body.expected_updated_at);const parsed=marketingCampaignSchema.safeParse(body);if(!parsed.success)return Response.json({error:'Confira os dados da campanha.',details:parsed.error.flatten()},{status:400});const campaign=await updateMarketingCampaign(id,parsed.data,expectedUpdatedAt);if(!campaign)return Response.json({error:'Campanha não encontrada.'},{status:404});await logAdminAction('update','marketing_campaign',id,`Campanha atualizada: ${campaign.name}`);return Response.json({campaign});}catch(e){if(e instanceof StaleWriteError||e instanceof CampaignSlugImmutableError)return Response.json({error:e.message},{status:409});if((e instanceof Error?e.message:'').toLowerCase().includes('unique'))return Response.json({error:'Já existe uma campanha com esse identificador.'},{status:409});return await serverFailure('admin.campaigns.update',e);}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401});if(!sameOriginRequest(request))return Response.json({error:'Origem inválida.'},{status:403});const{id}=await params;if(!isUuid(id))return Response.json({error:'ID inválido.'},{status:400});try{const expectedUpdatedAt=expectedUpdatedAtFromRequest(request);if(!(await hasRecentAdminReauthentication()))return Response.json({error:'Confirme novamente sua identidade para excluir a campanha.',reauth_required:true},{status:428});await requireCriticalAuditIntent('delete_campaign','marketing_campaign',id,'Exclusão de campanha autorizada após step-up MFA.');const deleted=await deleteMarketingCampaign(id,expectedUpdatedAt);if(!deleted)return Response.json({error:'Campanha não encontrada.'},{status:404});await logAdminAction('delete','marketing_campaign',id,'Campanha de marketing excluída.');await recordAdminSecurityEventWithAlert({eventType:'critical_action',severity:'warning',summary:`Campanha de marketing excluída (${id}).`});return Response.json({ok:true});}catch(e){if(e instanceof StaleWriteError)return Response.json({error:e.message},{status:409});if(e instanceof CampaignHasLeadsError)return Response.json({error:e.message,lead_count:e.leadCount},{status:409});return await serverFailure('admin.campaigns.delete',e);}}
