'use client';
import { useEffect, useState } from 'react';
import { Pencil, Plus, Trash2, Upload } from 'lucide-react';
import type { Category } from '@/lib/db';
import { fetchJson } from '@/lib/client';
import MediaPicker from './MediaPicker';

const blank={slug:'',name:'',description:'',image_url:'',active:true,sort_order:0}; type Form=typeof blank;
function toForm(c:Category):Form{return{slug:c.slug,name:c.name,description:c.description,image_url:c.image_url||'',active:c.active,sort_order:c.sort_order};}
export default function CategoryManager({categories,setCategories,usageByName={},onDirtyChange}:{categories:Category[];setCategories:React.Dispatch<React.SetStateAction<Category[]>>;usageByName?:Record<string,number>;onDirtyChange?:(dirty:boolean)=>void}){
  const [form,setForm]=useState<Form>(blank); const [editing,setEditing]=useState<string|null>(null); const [editingUpdatedAt,setEditingUpdatedAt]=useState<string|null>(null); const [dirty,setDirty]=useState(false); useEffect(()=>{onDirtyChange?.(dirty);},[dirty,onDirtyChange]); useEffect(()=>()=>onDirtyChange?.(false),[onDirtyChange]); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false); const [uploading,setUploading]=useState(false);
  function set<K extends keyof Form>(k:K,v:Form[K]){setForm(p=>({...p,[k]:v}));setDirty(true);} function reset(){setForm(blank);setEditing(null);setEditingUpdatedAt(null);setDirty(false);setError('');setMessage('');}
  function slugify(){set('slug',form.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''));}
  async function save(e:React.FormEvent){e.preventDefault();if(loading)return;setLoading(true);setError('');setMessage('');const body={...form,image_url:form.image_url.trim()||null,sort_order:Number(form.sort_order)||0,...(editingUpdatedAt?{expected_updated_at:editingUpdatedAt}:{})};try{const data=await fetchJson<{category:Category}>(editing?`/api/admin/categories/${editing}`:'/api/admin/categories',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)},18000);if(editing)setCategories(prev=>prev.map(c=>c.id===editing?data.category:c).sort((a,b)=>a.sort_order-b.sort_order));else setCategories(prev=>[...prev,data.category].sort((a,b)=>a.sort_order-b.sort_order));setMessage(editing?'Categoria atualizada.':'Categoria criada.');setForm(blank);setEditing(null);setEditingUpdatedAt(null);setDirty(false);}catch(e){setError(e instanceof Error?e.message:'Erro ao salvar.');}finally{setLoading(false);}}
  async function remove(c:Category){if(!confirm(`Excluir a categoria “${c.name}”?`))return;setError('');try{await fetchJson(`/api/admin/categories/${c.id}?expected_updated_at=${encodeURIComponent(c.updated_at)}`,{method:'DELETE'});setCategories(prev=>prev.filter(x=>x.id!==c.id));}catch(e){setError(e instanceof Error?e.message:'Não foi possível excluir.');}}
  async function uploadFile(file?:File){if(!file)return;setUploading(true);setError('');const fd=new FormData();fd.append('file',file);try{const data=await fetchJson<{url:string}>('/api/admin/upload',{method:'POST',body:fd},30000);set('image_url',data.url);}catch(e){setError(e instanceof Error?e.message:'Upload indisponível. Você pode colar uma URL.');}finally{setUploading(false);}}
  return <div className="admin-layout">
    <form className="admin-panel form-grid" onSubmit={save}><div className="panel-title"><div><div className="eyebrow">Organização</div><h2>{editing?'Editar categoria':'Nova categoria'}</h2></div>{editing&&<button type="button" className="btn" onClick={reset}>Cancelar</button>}</div><div className="field"><label htmlFor="category-name">Nome</label><input id="category-name" value={form.name} onChange={e=>set('name',e.target.value)} onBlur={()=>!form.slug&&slugify()} required/></div><div className="field"><label htmlFor="category-slug">Slug</label><div className="inline-field"><input id="category-slug" value={form.slug} onChange={e=>set('slug',e.target.value)} required/><button type="button" className="btn" onClick={slugify}>Gerar</button></div></div><div className="field"><label htmlFor="category-description">Descrição (opcional)</label><textarea id="category-description" value={form.description} onChange={e=>set('description',e.target.value)}/></div><div className="field"><label htmlFor="category-image">Imagem da categoria (opcional)</label><input id="category-image" placeholder="https://..." value={form.image_url} onChange={e=>set('image_url',e.target.value)}/><div className="inline-actions"><label className="btn upload-inline"><Upload size={15}/>{uploading?'Enviando...':'Enviar imagem'}<input hidden type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>uploadFile(e.target.files?.[0])}/></label><MediaPicker onSelect={url=>set('image_url',url)}/></div></div><div className="field"><label htmlFor="category-sort">Ordem</label><input id="category-sort" type="number" min="0" value={form.sort_order} onChange={e=>set('sort_order',Number(e.target.value))}/></div><label className="switch-line"><input type="checkbox" checked={form.active} onChange={e=>set('active',e.target.checked)}/> Categoria ativa</label>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<button className="btn btn-primary" type="submit" disabled={loading}>{loading?'Salvando...':editing?'Salvar categoria':'Criar categoria'}</button></form>
    <section className="admin-panel"><div className="panel-title"><div><div className="eyebrow">Filtros públicos</div><h2>{categories.length} categoria(s)</h2></div><button className="btn btn-primary" type="button" onClick={reset}><Plus size={16}/> Nova</button></div><div className="admin-list">{categories.map(c=><div className="admin-item category-item" key={c.id}><div className="category-order">{c.sort_order}</div><div><h3>{c.name}</h3><div className="admin-meta"><span>/{c.slug}</span><span>{c.active?'Ativa':'Oculta'}</span><span>{usageByName[c.name]||0} produto(s)</span></div></div><div className="admin-buttons"><button className="icon-btn" type="button" aria-label={`Editar ${c.name}`} onClick={()=>{setEditing(c.id);setEditingUpdatedAt(c.updated_at);setDirty(false);setForm(toForm(c));window.scrollTo({top:0,behavior:'smooth'})}}><Pencil size={16}/></button><button className="icon-btn" type="button" disabled={(usageByName[c.name]||0)>0} title={(usageByName[c.name]||0)>0?'Remova ou mova os produtos antes de excluir':'Excluir categoria'} aria-label={`Excluir ${c.name}`} onClick={()=>remove(c)}><Trash2 size={16}/></button></div></div>)}</div></section>
  </div>;
}
