'use client';
import { useEffect, useState } from 'react';
import { HelpCircle, Pencil, Plus, Save, Trash2, X } from 'lucide-react';
import type { Faq } from '@/lib/db';
import { fetchJson } from '@/lib/client';

type Draft={question:string;answer:string;active:boolean;sort_order:number};
const empty:Draft={question:'',answer:'',active:true,sort_order:0};
export default function FaqManager({faqs,setFaqs,onDirtyChange}:{faqs:Faq[];setFaqs:React.Dispatch<React.SetStateAction<Faq[]>>;onDirtyChange?:(dirty:boolean)=>void}){
  const [editing,setEditing]=useState<Faq|null>(null);const [creating,setCreating]=useState(false);const [form,setForm]=useState<Draft>(empty);const [dirty,setDirty]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  useEffect(()=>{onDirtyChange?.(dirty);},[dirty,onDirtyChange]);useEffect(()=>()=>onDirtyChange?.(false),[onDirtyChange]);
  function change<K extends keyof Draft>(key:K,value:Draft[K]){setForm(p=>({...p,[key]:value}));setDirty(true);}
  function openNew(){setEditing(null);setCreating(true);setForm({...empty,sort_order:(faqs.at(-1)?.sort_order||0)+1});setDirty(false);setError('');}
  function openEdit(f:Faq){setCreating(false);setEditing(f);setForm({question:f.question,answer:f.answer,active:f.active,sort_order:f.sort_order});setDirty(false);setError('');}
  function close(){if(dirty&&!confirm('Há alterações não salvas. Fechar mesmo assim?'))return;setEditing(null);setCreating(false);setDirty(false);setError('');}
  async function save(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');try{const data=await fetchJson<{faq:Faq}>(editing?`/api/admin/faqs/${editing.id}`:'/api/admin/faqs',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,...(editing?{expected_updated_at:editing.updated_at}:{})})});setFaqs(prev=>editing?prev.map(x=>x.id===data.faq.id?data.faq:x).sort((a,b)=>a.sort_order-b.sort_order):[...prev,data.faq].sort((a,b)=>a.sort_order-b.sort_order));setDirty(false);setEditing(null);setCreating(false);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setLoading(false);}}
  async function remove(f:Faq){if(!confirm(`Excluir a pergunta “${f.question}”?`))return;try{await fetchJson(`/api/admin/faqs/${f.id}?expected_updated_at=${encodeURIComponent(f.updated_at)}`,{method:'DELETE'});setFaqs(prev=>prev.filter(x=>x.id!==f.id));}catch(e){setError(e instanceof Error?e.message:'Não foi possível excluir.');}}
  return <section className="admin-panel"><div className="panel-title"><div><div className="eyebrow">Conteúdo / SEO</div><h2>Perguntas frequentes</h2><p className="muted">As perguntas publicadas aparecem automaticamente na home e no JSON-LD de FAQ.</p></div><button type="button" className="btn btn-primary" onClick={openNew}><Plus size={16}/> Nova pergunta</button></div>{error&&<div className="error" role="alert">{error}</div>}<div className="faq-admin-list">{faqs.map(f=><article key={f.id} className={!f.active?'is-muted':''}><div><span className="faq-order">{String(f.sort_order).padStart(2,'0')}</span><div><strong>{f.question}</strong><p>{f.answer}</p><small>{f.active?'Publicada':'Oculta'}</small></div></div><div className="admin-buttons"><button type="button" className="icon-btn" aria-label={`Editar ${f.question}`} onClick={()=>openEdit(f)}><Pencil size={16}/></button><button type="button" className="icon-btn" aria-label={`Excluir ${f.question}`} onClick={()=>remove(f)}><Trash2 size={16}/></button></div></article>)}{!faqs.length&&<div className="empty"><HelpCircle size={28}/><strong>Nenhuma pergunta cadastrada.</strong><span>Adicione as dúvidas que seus clientes mais fazem.</span></div>}</div>{(creating||editing)&&<div className="admin-modal-backdrop" role="presentation"><form className="admin-modal" onSubmit={save} role="dialog" aria-modal="true" aria-label={editing?'Editar pergunta':'Nova pergunta'}><div className="panel-title"><h2>{editing?'Editar pergunta':'Nova pergunta'}</h2><button type="button" className="icon-btn" aria-label="Fechar" onClick={close}><X size={18}/></button></div><div className="field"><label htmlFor="adm-faqmanager-1">Pergunta</label><input id="adm-faqmanager-1" value={form.question} maxLength={240} onChange={e=>change('question',e.target.value)} required/></div><div className="field"><label htmlFor="adm-faqmanager-2">Resposta</label><textarea id="adm-faqmanager-2" value={form.answer} maxLength={3000} onChange={e=>change('answer',e.target.value)} required/></div><div className="row-2"><div className="field"><label htmlFor="adm-faqmanager-3">Ordem</label><input id="adm-faqmanager-3" type="number" min="0" value={form.sort_order} onChange={e=>change('sort_order',Number(e.target.value))}/></div><label className="check-row"><input type="checkbox" checked={form.active} onChange={e=>change('active',e.target.checked)}/> Publicar no site</label></div>{error&&<div className="error" role="alert">{error}</div>}<button className="btn btn-primary" type="submit" disabled={loading}><Save size={16}/>{loading?'Salvando...':'Salvar pergunta'}</button></form></div>}</section>;
}
