'use client';
import { useEffect, useState } from 'react';
import { Copy, Image as ImageIcon, LoaderCircle, RefreshCw, Trash2 } from 'lucide-react';
import { fetchJson } from '@/lib/client';
import SafeImage from '@/components/SafeImage';

type MediaItem={key:string;url:string;size:number;updated_at:string;unavailable?:boolean};
type MediaPage={configured:boolean;items:MediaItem[];next:string|null};
function sizeLabel(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`;}
export default function MediaManager(){const [items,setItems]=useState<MediaItem[]>([]);const [cursor,setCursor]=useState<string|null>(null);const [configured,setConfigured]=useState<boolean|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  async function load(next?:string|null,replace=false){setLoading(true);setError('');try{const q=next?`?cursor=${encodeURIComponent(next)}`:'';const data=await fetchJson<MediaPage>(`/api/admin/media${q}`);setConfigured(data.configured);setCursor(data.next);setItems(prev=>replace?data.items:[...prev,...data.items.filter(item=>!prev.some(p=>p.key===item.key))]);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a biblioteca.');}finally{setLoading(false);}}
  useEffect(()=>{void load(null,true);},[]);
  async function copy(url:string){try{await navigator.clipboard.writeText(url);setMessage('URL copiada.');setTimeout(()=>setMessage(''),1600);}catch{setError('Não foi possível copiar automaticamente.');}}
  async function remove(item:MediaItem){if(!confirm('Excluir este arquivo do Storage? Essa ação não pode ser desfeita.'))return;setError('');try{await fetchJson('/api/admin/media',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({url:item.url})});setItems(prev=>prev.filter(x=>x.key!==item.key));setMessage('Arquivo excluído.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível excluir.');}}
  return <section className="admin-panel"><div className="panel-title"><div><div className="eyebrow">Arquivos / Storage</div><h2>Biblioteca de mídia</h2><p className="muted">Veja imagens já enviadas. A exclusão é bloqueada enquanto o arquivo estiver em uso no catálogo.</p></div><button type="button" className="btn" onClick={()=>load(null,true)} disabled={loading}><RefreshCw size={16}/> Atualizar</button></div>{configured===false&&<div className="notice"><strong>Storage ainda não configurado.</strong><span>O catálogo continua aceitando URLs externas. Configure as variáveis S3 no RunSite para ativar uploads e esta biblioteca.</span></div>}{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}<div className="media-grid">{items.map(item=><article key={item.key}><div className="media-preview"><SafeImage src={item.url} alt="" loading="lazy" decoding="async"/></div><div className="media-info"><strong title={item.key}>{item.key.split('/').pop()}</strong><small>{item.unavailable?'Indisponível para uso • ':''}{sizeLabel(item.size)}{item.updated_at?` • ${new Date(item.updated_at).toLocaleDateString('pt-BR')}`:''}</small><div className="inline-actions"><button type="button" className="btn" onClick={()=>copy(item.url)} disabled={item.unavailable}><Copy size={14}/> Copiar URL</button><button type="button" className="icon-btn" aria-label={item.unavailable?'Tentar excluir arquivo novamente':'Excluir arquivo'} onClick={()=>remove(item)}><Trash2 size={15}/></button></div></div></article>)}{configured&&items.length===0&&!loading&&<div className="empty"><ImageIcon size={28}/><strong>Nenhuma imagem no Storage.</strong><span>Faça uploads pelo cadastro de produtos, categorias ou configurações.</span></div>}</div>{loading&&<div className="media-loading"><LoaderCircle className="spin" size={18}/> Carregando...</div>}{cursor&&<button type="button" className="btn media-more" onClick={()=>load(cursor)} disabled={loading}>Carregar mais arquivos</button>}</section>;
}
