'use client';
import { useState } from 'react';
import { AlertTriangle,Download,Eraser,Search,ShieldCheck,UserRoundSearch } from 'lucide-react';
import { fetchJson } from '@/lib/client';
import type { Inquiry,PrivacyExport,PrivacyLookupResult } from '@/lib/db';
import type { PrivacyIdentityType } from '@/lib/privacy';

function when(value:string|null){if(!value)return'—';try{return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value));}catch{return value;}}
function statusLabel(row:Inquiry){if(row.status==='fechado'&&row.production_status!=='entregue')return`${row.status} • produção ${row.production_status}`;return row.status;}

export default function PrivacyCenter(){
  const [type,setType]=useState<PrivacyIdentityType>('phone');const [value,setValue]=useState('');const [result,setResult]=useState<PrivacyLookupResult|null>(null);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [confirmation,setConfirmation]=useState('');
  async function lookup(){setBusy('lookup');setError('');setMessage('');setConfirmation('');try{const data=await fetchJson<{result:PrivacyLookupResult}>('/api/admin/privacy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'lookup',identity_type:type,value})},18000);setResult(data.result);}catch(e){setResult(null);setError(e instanceof Error?e.message:'Não foi possível localizar os dados.');}finally{setBusy('');}}
  async function exportData(){setBusy('export');setError('');setMessage('');try{const response=await fetchJson<{data:PrivacyExport}>('/api/admin/privacy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'export',identity_type:type,value})},30000);const blob=new Blob([JSON.stringify({export_format:'marques-privacy-v1',...response.data},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`dados-cliente-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setMessage('Exportação individual preparada. O arquivo contém apenas os registros associados ao identificador consultado.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível exportar os dados.');}finally{setBusy('');}}
  async function anonymize(){if(confirmation!=='ANONIMIZAR'){setError('Digite ANONIMIZAR para confirmar a anonimização.');return;}setBusy('anonymize');setError('');setMessage('');try{const response=await fetchJson<{ok:boolean;result:{anonymized:number;activity_deleted:number;snapshots_deleted:number};external_backups_warning:string}>('/api/admin/privacy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'anonymize',identity_type:type,value,confirmation})},60000);setMessage(`${response.result.anonymized} atendimento(s) anonimizado(s); ${response.result.activity_deleted} evento(s) de timeline removido(s). ${response.external_backups_warning}`);setConfirmation('');const refreshed=await fetchJson<{result:PrivacyLookupResult}>('/api/admin/privacy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'lookup',identity_type:type,value})},18000);setResult(refreshed.result);}catch(e){setError(e instanceof Error?e.message:'Não foi possível anonimizar os dados.');}finally{setBusy('');}}
  return <section className="admin-panel privacy-center"><div className="panel-subtitle"><div><div className="eyebrow">Privacidade & ciclo de vida</div><h2>Dados pessoais do CRM</h2><p className="muted">Localize uma pessoa por correspondência exata, exporte os dados associados ou anonimize registros encerrados sem apagar métricas financeiras do negócio.</p></div><ShieldCheck size={24}/></div>
    <div className="security-block"><div className="security-block-head"><div><h3>Localização exata</h3><p>O identificador é enviado no corpo de uma requisição administrativa e não aparece na URL. A trilha administrativa registra apenas o tipo e as contagens, nunca o WhatsApp/e-mail pesquisado.</p></div><UserRoundSearch size={21}/></div><div className="crm-fields"><label>Tipo<select value={type} onChange={e=>{setType(e.target.value as PrivacyIdentityType);setResult(null);setMessage('');setError('');}}><option value="phone">WhatsApp</option><option value="email">E-mail</option></select></label><label>{type==='phone'?'WhatsApp completo':'E-mail completo'}<input value={value} onChange={e=>setValue(e.target.value)} autoComplete="off" placeholder={type==='phone'?'Ex.: (98) 99999-9999':'cliente@exemplo.com'} onKeyDown={e=>{if(e.key==='Enter')void lookup();}}/></label></div><button type="button" className="btn btn-primary" onClick={()=>void lookup()} disabled={!value.trim()||Boolean(busy)}><Search size={15}/>{busy==='lookup'?'Consultando…':'Buscar correspondência exata'}</button></div>
    {result&&<div className="security-block"><div className="security-block-head"><div><h3>Resultado</h3><p>{result.matched} atendimento(s) atual(is) encontrado(s). {result.previously_anonymized?'Existe tombstone de anonimização para esta identidade.':'Nenhuma anonimização anterior registrada para esta identidade.'}</p></div><span className={`status-pill ${result.active?'warning':'active'}`}>{result.active?`${result.active} exigem ação`:'Elegível para anonimização'}</span></div>{result.items.length>0?<div className="audit-stream">{result.items.map(row=><article key={row.id}><span className={`audit-dot ${result.active?'warning':'info'}`}/><div><strong>{row.product_name||row.category||'Atendimento'}</strong><small>{statusLabel(row)} • criado em {when(row.created_at)} • atualizado {when(row.updated_at)}</small><code>{row.id}</code></div></article>)}</div>:<div className="empty-state">Nenhum registro atual contém esse identificador. Uma tombstone existente continua protegendo restores futuros.</div>}
      <div className="privacy-actions"><button type="button" className="btn" disabled={Boolean(busy)} onClick={()=>void exportData()}><Download size={15}/>{busy==='export'?'Preparando…':'Exportar dados da pessoa'}</button></div>
      <div className="operation-warning"><AlertTriangle size={19}/><div><strong>Anonimização irreversível no CRM ativo</strong><p>Nome, contato, textos livres, personalizações e timeline serão removidos. Valores, status comerciais e dados agregados permanecem para contabilidade e métricas. Snapshots internos de restore serão descartados para não reintroduzir os dados.</p><p>Backups JSON que já tenham sido baixados ficam fora do alcance do site e precisam obedecer à política de retenção/eliminação do negócio.</p></div></div>
      <div className="crm-fields"><label>Confirmação<input value={confirmation} onChange={e=>setConfirmation(e.target.value.toUpperCase())} placeholder="Digite ANONIMIZAR" autoComplete="off"/></label></div><button type="button" className="btn btn-danger-soft" disabled={Boolean(busy)||result.active>0||confirmation!=='ANONIMIZAR'} onClick={()=>void anonymize()}><Eraser size={15}/>{busy==='anonymize'?'Anonimizando…':'Anonimizar dados pessoais'}</button>{result.active>0&&<p className="muted">Finalize/encerre os atendimentos ativos e conclua qualquer produção antes da anonimização.</p>}
    </div>}
    {error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
  </section>;
}
