'use client';
import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowDown, ArrowUp, CalendarClock, Copy, Download, ExternalLink, Eye, EyeOff, Pencil, Plus, Sparkles, Star, Trash2, Upload } from 'lucide-react';
import type { Category, Product, ProductBulkAction, ProductCustomizationField } from '@/lib/db';
import { fetchJson } from '@/lib/client';
import SafeImage from '@/components/SafeImage';
import MediaPicker from './MediaPicker';
import ProductCsvImport from './ProductCsvImport';
import { productPublishIssues } from '@/lib/product-readiness';

const DRAFT_KEY='marques.admin.product-draft.v1';
const blank={slug:'',name:'',category:'',description:'',price:'',image_urls:[''],featured:false,active:false,stock_status:'sob_encomenda' as Product['stock_status'],tags:'',sort_order:0,min_quantity:'',production_time:'',seo_title:'',seo_description:'',badge:'',customization_fields:[] as ProductCustomizationField[],publish_at:'',unpublish_at:''};
type FormState=typeof blank;
function toLocal(value:string|null){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return'';const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}
function fromLocal(value:string){if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d.toISOString();}
function fromProduct(p:Product):FormState{return{slug:p.slug,name:p.name,category:p.category,description:p.description,price:p.price_cents===null?'':String((p.price_cents/100).toFixed(2)).replace('.',','),image_urls:p.image_urls.length?p.image_urls:[''],featured:p.featured,active:p.active,stock_status:p.stock_status,tags:p.tags.join(', '),sort_order:p.sort_order,min_quantity:p.min_quantity?String(p.min_quantity):'',production_time:p.production_time||'',seo_title:p.seo_title||'',seo_description:p.seo_description||'',badge:p.badge||'',customization_fields:p.customization_fields||[],publish_at:toLocal(p.publish_at),unpublish_at:toLocal(p.unpublish_at)};}
function fieldId(label:string,index:number){const id=label.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,32);return id||`campo-${index+1}`;}
function visibilityLabel(p:Product){const now=Date.now();if(!p.active)return'Oculto';if(p.publish_at&&new Date(p.publish_at).getTime()>now)return'Agendado';if(p.unpublish_at&&new Date(p.unpublish_at).getTime()<=now)return'Encerrado';return'Publicado';}
function qualityScore(p:Product){let score=0;if(p.image_urls.length)score+=25;if(p.description.trim().length>=80)score+=20;if(p.production_time.trim())score+=15;if(p.tags.length>=2)score+=10;if(p.seo_title.trim())score+=10;if(p.seo_description.trim())score+=10;if(p.category)score+=10;return score;}
type CatalogFilter='todos'|'mais-vistos'|'incompletos'|'agendados'|'personalizaveis'|'sem-imagem'|'sem-seo';

export default function ProductManager({products,setProducts,categories,viewsBySlug={},onDirtyChange}:{products:Product[];setProducts:React.Dispatch<React.SetStateAction<Product[]>>;categories:Category[];viewsBySlug?:Record<string,number>;onDirtyChange?:(dirty:boolean)=>void}){
  const firstCategory=categories[0]?.name||'Topos de bolo';
  const [form,setForm]=useState<FormState>({...blank,category:firstCategory});
  const [editingId,setEditingId]=useState<string|null>(null);const [editingUpdatedAt,setEditingUpdatedAt]=useState<string|null>(null);const [dirty,setDirty]=useState(false);
  const [message,setMessage]=useState('');const [draftReady,setDraftReady]=useState(false);const [draftCandidate,setDraftCandidate]=useState<{form:FormState;editingId:string|null;editingUpdatedAt:string|null;savedAt:number}|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [uploading,setUploading]=useState(false);const [query,setQuery]=useState('');const [filter,setFilter]=useState<CatalogFilter>('todos');const [selected,setSelected]=useState<Set<string>>(new Set());const [bulkLoading,setBulkLoading]=useState(false);const [bulkCategoryId,setBulkCategoryId]=useState('');
  useEffect(()=>{onDirtyChange?.(dirty);},[dirty,onDirtyChange]);useEffect(()=>()=>onDirtyChange?.(false),[onDirtyChange]);
  useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(raw&&raw.form&&Date.now()-Number(raw.savedAt||0)<7*86400000)setDraftCandidate(raw);}catch{}finally{setDraftReady(true);}},[]);
  useEffect(()=>{if(!draftReady)return;try{if(dirty)localStorage.setItem(DRAFT_KEY,JSON.stringify({form,editingId,editingUpdatedAt,savedAt:Date.now()}));else if(!draftCandidate)localStorage.removeItem(DRAFT_KEY);}catch{}},[draftReady,dirty,form,editingId,editingUpdatedAt,draftCandidate]);
  const shown=useMemo(()=>{const now=Date.now();let data=[...products];if(filter==='mais-vistos')data.sort((a,b)=>(viewsBySlug[b.slug]||0)-(viewsBySlug[a.slug]||0));if(filter==='incompletos')data=data.filter(p=>qualityScore(p)<80);if(filter==='agendados')data=data.filter(p=>p.active&&Boolean(p.publish_at)&&new Date(p.publish_at!).getTime()>now);if(filter==='personalizaveis')data=data.filter(p=>p.customization_fields.length>0);if(filter==='sem-imagem')data=data.filter(p=>!p.image_urls.length);if(filter==='sem-seo')data=data.filter(p=>!p.seo_title.trim()||!p.seo_description.trim());const q=query.trim().toLowerCase();return q?data.filter(p=>`${p.name} ${p.category} ${p.tags.join(' ')} ${p.badge}`.toLowerCase().includes(q)):data;},[products,query,filter,viewsBySlug]);
  const formPublishIssues=useMemo(()=>productPublishIssues({name:form.name,slug:form.slug,category:form.category,description:form.description,image_urls:form.image_urls,production_time:form.production_time}),[form.name,form.slug,form.category,form.description,form.image_urls,form.production_time]);
  function set<K extends keyof FormState>(key:K,value:FormState[K]){setForm(prev=>({...prev,[key]:value}));setDirty(true);}
  function discardDraft(){try{localStorage.removeItem(DRAFT_KEY);}catch{}setDraftCandidate(null);}
  function restoreDraft(){if(!draftCandidate)return;setForm(draftCandidate.form);setEditingId(draftCandidate.editingId);setEditingUpdatedAt(draftCandidate.editingUpdatedAt);setDirty(true);setMessage('Rascunho local restaurado. Revise antes de salvar.');setDraftCandidate(null);}
  function reset(){try{localStorage.removeItem(DRAFT_KEY);}catch{}setDraftCandidate(null);setForm({...blank,category:firstCategory});setEditingId(null);setEditingUpdatedAt(null);setDirty(false);setMessage('');setError('');}
  function slugify(){set('slug',form.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''));}
  function updateCustom(index:number,patch:Partial<ProductCustomizationField>){set('customization_fields',form.customization_fields.map((f,i)=>i===index?{...f,...patch}:f));}
  function addCustom(){if(form.customization_fields.length>=8)return;const index=form.customization_fields.length;set('customization_fields',[...form.customization_fields,{id:`campo-${index+1}`,label:'',type:'text',required:false,placeholder:'',options:[]}]);}
  function removeCustom(index:number){set('customization_fields',form.customization_fields.filter((_,i)=>i!==index));}
  function moveImage(index:number,dir:-1|1){const target=index+dir;if(target<0||target>=form.image_urls.length)return;const next=[...form.image_urls];[next[index],next[target]]=[next[target],next[index]];set('image_urls',next);}
  async function save(e:React.FormEvent){
    e.preventDefault();if(loading)return;setLoading(true);setError('');setMessage('');
    const parsedPrice=form.price.trim()===''?null:Math.round(Number(form.price.replace(',','.'))*100);
    const fields=form.customization_fields.map((field,index)=>({...field,id:fieldId(field.label||field.id,index),label:field.label.trim(),placeholder:(field.placeholder||'').trim(),options:field.type==='select'?field.options.map(x=>x.trim()).filter(Boolean):[]}));
    const body={slug:form.slug,name:form.name,category:form.category||firstCategory,description:form.description,price_cents:Number.isFinite(parsedPrice as number)?parsedPrice:null,image_urls:form.image_urls.map(v=>v.trim()).filter(Boolean),featured:form.featured,active:form.active,stock_status:form.stock_status,tags:form.tags.split(',').map(v=>v.trim()).filter(Boolean),sort_order:Number(form.sort_order)||0,min_quantity:form.min_quantity?Number(form.min_quantity):null,production_time:form.production_time,seo_title:form.seo_title,seo_description:form.seo_description,badge:form.badge,customization_fields:fields,publish_at:fromLocal(form.publish_at),unpublish_at:fromLocal(form.unpublish_at),...(editingUpdatedAt?{expected_updated_at:editingUpdatedAt}:{})};
    try{const data=await fetchJson<{product:Product}>(editingId?`/api/admin/products/${editingId}`:'/api/admin/products',{method:editingId?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)},18000);if(editingId)setProducts(prev=>prev.map(p=>p.id===editingId?data.product:p));else setProducts(prev=>[data.product,...prev]);try{localStorage.removeItem(DRAFT_KEY);}catch{}setDraftCandidate(null);setMessage(editingId?'Produto atualizado.':'Produto cadastrado.');setForm({...blank,category:firstCategory});setEditingId(null);setEditingUpdatedAt(null);setDirty(false);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setLoading(false);}
  }
  function duplicate(p:Product){const copy=fromProduct(p);setEditingId(null);setEditingUpdatedAt(null);setDirty(true);setForm({...copy,name:`${p.name} — cópia`,slug:`${p.slug}-copia-${Date.now().toString(36).slice(-4)}`,featured:false,active:false,publish_at:'',unpublish_at:''});setMessage('Cópia criada como rascunho. Revise e salve como novo produto.');setError('');window.scrollTo({top:0,behavior:'smooth'});}
  async function remove(p:Product){if(!confirm(`Arquivar “${p.name}”? Ele sairá do site e poderá ser restaurado pela Lixeira.`))return;setError('');try{await fetchJson(`/api/admin/products/${p.id}?expected_updated_at=${encodeURIComponent(p.updated_at)}`,{method:'DELETE'});setProducts(prev=>prev.filter(x=>x.id!==p.id));setSelected(prev=>{const next=new Set(prev);next.delete(p.id);return next;});}catch(e){setError(e instanceof Error?e.message:'Não foi possível excluir.');}}
  async function uploadFile(file?:File){if(!file)return;setUploading(true);setError('');const fd=new FormData();fd.append('file',file);try{const data=await fetchJson<{url:string}>('/api/admin/upload',{method:'POST',body:fd},30000);set('image_urls',[data.url,...form.image_urls.filter(Boolean)]);}catch(e){setError(e instanceof Error?e.message:'Upload indisponível.');}finally{setUploading(false);}}
  function toggleSelected(id:string){setSelected(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next;});}
  function selectShown(){setSelected(prev=>{const next=new Set(prev);const all=shown.every(p=>next.has(p.id));for(const p of shown)all?next.delete(p.id):next.add(p.id);return next;});}
  async function bulk(action:ProductBulkAction){if(!selected.size||bulkLoading)return;setBulkLoading(true);setError('');try{const data=await fetchJson<{products:Product[];count:number}>('/api/admin/products/bulk',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({items:products.filter(p=>selected.has(p.id)).map(p=>({id:p.id,updated_at:p.updated_at})),action,...(action==='move_category'?{category_id:bulkCategoryId}:{})})},18000);const map=new Map(data.products.map(p=>[p.id,p]));setProducts(prev=>prev.map(p=>map.get(p.id)||p));setMessage(`${data.count} produto(s) atualizado(s) em lote.`);setSelected(new Set());}catch(e){setError(e instanceof Error?e.message:'Não foi possível aplicar a ação em lote.');}finally{setBulkLoading(false);}}
  return <div className="admin-layout product-manager-v2">
    {draftCandidate&&<div className="admin-draft-recovery" role="status"><div><strong>Rascunho local encontrado</strong><span>Há uma edição de produto não salva de {new Date(draftCandidate.savedAt).toLocaleString('pt-BR')}.</span></div><div><button type="button" className="btn btn-primary" onClick={restoreDraft}>Restaurar</button><button type="button" className="btn" onClick={discardDraft}>Descartar</button></div></div>}
    <form className="admin-panel form-grid" onSubmit={save}>
      <div className="panel-title"><div><div className="eyebrow">Produto</div><h2>{editingId?'Editar produto':'Novo produto'}</h2><p className="muted small">Cadastro comercial, publicação, personalização e SEO em um só lugar.</p></div>{editingId&&<button className="btn" type="button" onClick={reset}>Cancelar</button>}</div>
      <div className="field"><label htmlFor="product-name">Nome</label><input id="product-name" maxLength={120} value={form.name} onChange={e=>set('name',e.target.value)} onBlur={()=>!form.slug&&slugify()} required/></div>
      <div className="field"><label htmlFor="product-slug">Slug da página</label><div className="inline-field"><input id="product-slug" value={form.slug} onChange={e=>set('slug',e.target.value)} required/><button className="btn" type="button" onClick={slugify}>Gerar</button></div></div>
      <div className="row-2"><div className="field"><label htmlFor="product-category">Categoria</label><select id="product-category" value={form.category||firstCategory} onChange={e=>set('category',e.target.value)}>{categories.map(c=><option key={c.id}>{c.name}</option>)}</select></div><div className="field"><label htmlFor="product-stock">Status comercial</label><select id="product-stock" value={form.stock_status} onChange={e=>set('stock_status',e.target.value as Product['stock_status'])}><option value="sob_encomenda">Sob encomenda</option><option value="disponivel">Disponível</option><option value="indisponivel">Indisponível</option></select></div></div>
      <div className="field"><label htmlFor="product-description">Descrição</label><textarea id="product-description" maxLength={3000} value={form.description} onChange={e=>set('description',e.target.value)} required/></div>
      <div className="row-2"><div className="field"><label htmlFor="product-price">Preço inicial (R$)</label><input id="product-price" inputMode="decimal" placeholder="Vazio = sob consulta" value={form.price} onChange={e=>set('price',e.target.value)}/></div><div className="field"><label htmlFor="product-min">Pedido mínimo</label><input id="product-min" type="number" min="1" placeholder="Ex.: 10" value={form.min_quantity} onChange={e=>set('min_quantity',e.target.value)}/></div></div>
      <div className="row-2"><div className="field"><label htmlFor="product-production">Prazo de produção</label><input id="product-production" maxLength={100} placeholder="Ex.: 5 a 7 dias úteis" value={form.production_time} onChange={e=>set('production_time',e.target.value)}/></div><div className="field"><label htmlFor="product-badge">Badge comercial</label><input id="product-badge" maxLength={30} placeholder="Ex.: Mais pedido / Novo" value={form.badge} onChange={e=>set('badge',e.target.value)}/></div></div>
      <div className="row-2"><div className="field"><label htmlFor="product-publish-at">Publicar a partir de</label><div className="field-icon"><CalendarClock size={16}/><input id="product-publish-at" type="datetime-local" value={form.publish_at} onChange={e=>set('publish_at',e.target.value)}/></div></div><div className="field"><label htmlFor="product-unpublish-at">Retirar automaticamente em</label><div className="field-icon"><CalendarClock size={16}/><input id="product-unpublish-at" type="datetime-local" value={form.unpublish_at} onChange={e=>set('unpublish_at',e.target.value)}/></div></div></div>
      <div className="field"><label htmlFor="product-sort">Ordem manual</label><input id="product-sort" type="number" min="0" value={form.sort_order} onChange={e=>set('sort_order',Number(e.target.value))}/></div>
      <div className="field"><span className="field-label">Imagens</span><div className="admin-image-editor">{form.image_urls.map((url,i)=><div className="admin-image-row" key={i}><div className="admin-image-preview"><SafeImage src={url||'/placeholder-topo.svg'} alt=""/></div><input placeholder="https://..." value={url} onChange={e=>{const urls=[...form.image_urls];urls[i]=e.target.value;set('image_urls',urls)}}/><div className="admin-image-actions"><button className="icon-btn" type="button" disabled={i===0} onClick={()=>moveImage(i,-1)} aria-label="Mover imagem para cima"><ArrowUp size={14}/></button><button className="icon-btn" type="button" disabled={i===form.image_urls.length-1} onClick={()=>moveImage(i,1)} aria-label="Mover imagem para baixo"><ArrowDown size={14}/></button>{form.image_urls.length>1&&<button className="icon-btn danger" type="button" onClick={()=>set('image_urls',form.image_urls.filter((_,x)=>x!==i))} aria-label="Remover imagem"><Trash2 size={14}/></button>}</div></div>)}</div><div className="inline-actions"><button type="button" className="btn" onClick={()=>set('image_urls',[...form.image_urls,''])}>+ URL</button><label className="btn"><Upload size={16}/>{uploading?'Enviando...':'Upload'}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>uploadFile(e.target.files?.[0])} disabled={uploading}/></label><MediaPicker onSelect={url=>set('image_urls',[url,...form.image_urls.filter(Boolean)])}/></div></div>
      <div className="field"><label htmlFor="product-tags">Tags</label><input id="product-tags" placeholder="premium, 3D, aniversário" value={form.tags} onChange={e=>set('tags',e.target.value)}/></div>
      <section className="customization-admin"><div className="panel-subhead"><div><span className="eyebrow">Personalização</span><h3>Campos que o cliente poderá preencher</h3><p className="muted small">Ex.: nome, idade, cor, acabamento. Máximo de 8 campos por produto.</p></div><button type="button" className="btn" onClick={addCustom} disabled={form.customization_fields.length>=8}><Plus size={15}/> Campo</button></div>{form.customization_fields.length===0?<div className="empty compact">Este produto usa apenas o briefing geral do evento.</div>:<div className="customization-admin-list">{form.customization_fields.map((field,index)=><div className="customization-admin-row" key={`${field.id}-${index}`}><div className="row-2"><div className="field"><label htmlFor={`custom-label-${field.id}-${index}`}>Nome do campo</label><input id={`custom-label-${field.id}-${index}`} maxLength={60} placeholder="Ex.: Nome" value={field.label} onChange={e=>updateCustom(index,{label:e.target.value,id:fieldId(e.target.value,index)})}/></div><div className="field"><label htmlFor={`custom-type-${field.id}-${index}`}>Tipo</label><select id={`custom-type-${field.id}-${index}`} value={field.type} onChange={e=>updateCustom(index,{type:e.target.value as ProductCustomizationField['type']})}><option value="text">Texto</option><option value="number">Número</option><option value="select">Lista de opções</option></select></div></div><div className="row-2"><div className="field"><label htmlFor={`custom-placeholder-${field.id}-${index}`}>Exemplo / placeholder</label><input id={`custom-placeholder-${field.id}-${index}`} maxLength={80} value={field.placeholder||''} onChange={e=>updateCustom(index,{placeholder:e.target.value})}/></div><div className="field"><label className="check-inline"><input type="checkbox" checked={field.required} onChange={e=>updateCustom(index,{required:e.target.checked})}/> Obrigatório</label></div></div>{field.type==='select'&&<div className="field"><label htmlFor={`custom-options-${field.id}-${index}`}>Opções (uma por linha)</label><textarea id={`custom-options-${field.id}-${index}`} rows={3} value={field.options.join('\n')} onChange={e=>updateCustom(index,{options:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})}/></div>}<button type="button" className="btn btn-danger-soft" onClick={()=>removeCustom(index)}><Trash2 size={14}/> Remover campo</button></div>)}</div>}</section>
      <details className="form-details"><summary>SEO da página do produto</summary><div className="field"><label htmlFor="product-seo-title">Título SEO (até 70 caracteres)</label><input id="product-seo-title" maxLength={70} placeholder="Vazio = usa o nome do produto" value={form.seo_title} onChange={e=>set('seo_title',e.target.value)}/><small>{form.seo_title.length}/70</small></div><div className="field"><label htmlFor="product-seo-description">Descrição SEO</label><textarea id="product-seo-description" maxLength={170} placeholder="Vazio = usa a descrição do produto" value={form.seo_description} onChange={e=>set('seo_description',e.target.value)}/><small>{form.seo_description.length}/170</small></div><div className="seo-preview"><small>Prévia</small><strong>{form.seo_title||form.name||'Título do produto'}</strong><span>seudominio.com/catalogo/{form.slug||'produto'}</span><p>{form.seo_description||form.description.slice(0,150)||'Descrição do produto para resultados de busca.'}</p></div></details>
      <div className={`publish-readiness ${formPublishIssues.length?'pending':'ready'}`}><div><strong>{formPublishIssues.length?'Rascunho ainda não pronto para publicação':'Pronto para publicar'}</strong><span>{formPublishIssues.length?`Falta: ${formPublishIssues.join(' • ')}`:'Os requisitos mínimos da vitrine estão completos.'}</span></div><span>{formPublishIssues.length?`${formPublishIssues.length} pendência(s)`:'OK'}</span></div>
      <div className="checks"><label><input type="checkbox" checked={form.featured} onChange={e=>set('featured',e.target.checked)}/> Destaque</label><label><input type="checkbox" checked={form.active} onChange={e=>set('active',e.target.checked)}/> Publicação habilitada</label></div>
      {error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
      <button className="btn btn-primary" type="submit" disabled={loading}>{loading?'Salvando...':editingId?'Salvar alterações':'Cadastrar produto'}</button>
    </form>
    <section className="admin-panel"><div className="panel-title"><div><div className="eyebrow">Catálogo</div><h2>{products.length} produto(s)</h2></div><button className="btn btn-primary" type="button" onClick={reset}><Plus size={16}/> Novo</button></div>
      <div className="product-admin-toolbar"><div className="field admin-search"><input placeholder="Buscar produto, tag, categoria ou badge..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="field admin-filter"><select aria-label="Filtrar catálogo administrativo" value={filter} onChange={e=>setFilter(e.target.value as CatalogFilter)}><option value="todos">Todos</option><option value="mais-vistos">Mais vistos</option><option value="incompletos">Qualidade abaixo de 80%</option><option value="agendados">Agendados</option><option value="personalizaveis">Personalizáveis</option><option value="sem-imagem">Sem imagem</option><option value="sem-seo">SEO incompleto</option></select></div><a className="btn" href="/api/admin/products/export" title="Exportar catálogo em CSV"><Download size={15}/> CSV</a><ProductCsvImport onImported={items=>setProducts(prev=>[...items,...prev.filter(p=>!items.some(item=>item.id===p.id))])}/><button className="btn" type="button" onClick={selectShown}>{shown.length&&shown.every(p=>selected.has(p.id))?'Desmarcar exibidos':'Selecionar exibidos'}</button></div>
      {selected.size>0&&<div className="bulk-toolbar" role="region" aria-label="Ações em lote"><strong>{selected.size} selecionado(s)</strong><button type="button" className="btn" disabled={bulkLoading} onClick={()=>bulk('publish')}><Eye size={15}/> Publicar</button><button type="button" className="btn" disabled={bulkLoading} onClick={()=>bulk('hide')}><EyeOff size={15}/> Ocultar</button><button type="button" className="btn" disabled={bulkLoading} onClick={()=>bulk('feature')}><Star size={15}/> Destacar</button><button type="button" className="btn" disabled={bulkLoading} onClick={()=>bulk('unfeature')}><Sparkles size={15}/> Remover destaque</button><div className="bulk-move"><select aria-label="Categoria de destino" value={bulkCategoryId} onChange={e=>setBulkCategoryId(e.target.value)}><option value="">Mover para categoria…</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button type="button" className="btn" disabled={bulkLoading||!bulkCategoryId} onClick={()=>bulk('move_category')}>Mover</button></div></div>}
      <div className="admin-list">{shown.map(p=><div className={`admin-item ${selected.has(p.id)?'selected':''}`} key={p.id}><label className="admin-select"><input type="checkbox" checked={selected.has(p.id)} onChange={()=>toggleSelected(p.id)} aria-label={`Selecionar ${p.name}`}/></label><SafeImage className="admin-thumb" src={p.image_urls[0]||'/placeholder-topo.svg'} alt=""/><div className="admin-item-copy"><div className="admin-product-title-row"><h3>{p.name}</h3><span className={`catalog-quality-chip ${qualityScore(p)<80?'attention':''}`} title="Completude do cadastro">{qualityScore(p)<80&&<AlertTriangle size={12}/>} {qualityScore(p)}%</span></div><div className="admin-meta"><span>{p.category}</span><span>{visibilityLabel(p)}</span>{p.featured&&<span className="gold-text">Destaque</span>}{p.badge&&<span>{p.badge}</span>}{p.customization_fields.length>0&&<span>{p.customization_fields.length} campo(s)</span>}{(viewsBySlug[p.slug]||0)>0&&<span className="view-count">{viewsBySlug[p.slug]} visualização(ões)</span>}</div>{p.publish_at&&<small className="schedule-note">Publicação: {new Date(p.publish_at).toLocaleString('pt-BR')}</small>}</div><div className="admin-buttons"><a className="icon-btn" href={`/catalogo/${p.slug}${visibilityLabel(p)==='Publicado'?'':'?preview=1'}`} target="_blank" rel="noreferrer" aria-label={`Ver página de ${p.name}`} title="Ver página"><ExternalLink size={16}/></a><button className="icon-btn" type="button" aria-label={`Duplicar ${p.name} como rascunho`} title="Duplicar como rascunho" onClick={()=>duplicate(p)}><Copy size={16}/></button><button className="icon-btn" type="button" aria-label={`Editar ${p.name}`} title="Editar" onClick={()=>{setEditingId(p.id);setEditingUpdatedAt(p.updated_at);setDirty(false);setForm(fromProduct(p));window.scrollTo({top:0,behavior:'smooth'})}}><Pencil size={16}/></button><button className="icon-btn" type="button" aria-label={`Excluir ${p.name}`} title="Excluir" onClick={()=>remove(p)}><Trash2 size={16}/></button></div></div>)}{!shown.length&&<div className="empty">Nenhum produto encontrado.</div>}</div>
    </section>
  </div>;
}
