'use client';
import { useRef,useState } from 'react';
import { FileUp, Upload, X } from 'lucide-react';
import type { Product } from '@/lib/db';
import { fetchJson } from '@/lib/client';

type PreviewRow={row:number;name:string;slug:string;category:string;ok:boolean;errors:string[]};
export default function ProductCsvImport({onImported}:{onImported:(products:Product[])=>void}){
  const [open,setOpen]=useState(false);const [csv,setCsv]=useState('');const [fileName,setFileName]=useState('');const [rows,setRows]=useState<PreviewRow[]>([]);const [valid,setValid]=useState(0);const [invalid,setInvalid]=useState(0);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const inputRef=useRef<HTMLInputElement>(null);
  function reset(){setOpen(false);setCsv('');setFileName('');setRows([]);setValid(0);setInvalid(0);setError('');if(inputRef.current)inputRef.current.value='';}
  async function choose(file?:File){if(!file)return;if(file.size>850_000){setError('O CSV deve ter menos de 850 KB.');return;}const text=await file.text();setCsv(text);setFileName(file.name);setRows([]);setError('');}
  async function preview(){if(!csv)return;setLoading(true);setError('');try{const data=await fetchJson<{rows:PreviewRow[];valid:number;invalid:number}>('/api/admin/products/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({csv,commit:false})},25000);setRows(data.rows);setValid(data.valid);setInvalid(data.invalid);}catch(e){setError(e instanceof Error?e.message:'Não foi possível validar o CSV.');}finally{setLoading(false);}}
  async function commit(){if(!csv||!valid)return;setLoading(true);setError('');try{const data=await fetchJson<{products:Product[];created:number;failed:{row:number;name:string;errors:string[]}[]}>('/api/admin/products/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({csv,commit:true})},60000);onImported(data.products);if(data.failed.length){setError(`${data.created} rascunho(s) importado(s); ${data.failed.length} linha(s) não foram criadas.`);setRows(data.failed.map(x=>({row:x.row,name:x.name,slug:'',category:'',ok:false,errors:x.errors})));setValid(0);setInvalid(data.failed.length);}else reset();}catch(e){setError(e instanceof Error?e.message:'Não foi possível importar o CSV.');}finally{setLoading(false);}}
  return <>{<button type="button" className="btn" onClick={()=>setOpen(true)}><FileUp size={15}/> Importar CSV</button>}{open&&<div className="admin-modal-backdrop" role="presentation"><section className="admin-modal csv-import-modal" role="dialog" aria-modal="true" aria-labelledby="csv-import-title"><div className="panel-title"><div><div className="eyebrow">Catálogo / lote</div><h2 id="csv-import-title">Importar produtos em CSV</h2><p className="muted small">Até 100 linhas. Tudo entra como rascunho oculto, nunca como publicação automática.</p></div><button type="button" className="icon-btn" onClick={reset} aria-label="Fechar importação"><X size={18}/></button></div><label className="csv-drop"><Upload size={22}/><strong>{fileName||'Selecionar arquivo CSV'}</strong><span>Use “;” como separador. O CSV exportado pelo painel já está no formato recomendado.</span><input ref={inputRef} hidden type="file" accept=".csv,text/csv" onChange={e=>choose(e.target.files?.[0])}/></label>{error&&<div className="error" role="alert">{error}</div>}{csv&&!rows.length&&<button type="button" className="btn btn-primary" onClick={preview} disabled={loading}>{loading?'Validando…':'Validar e visualizar'}</button>}{rows.length>0&&<><div className="csv-import-summary"><span><b>{valid}</b> válidas</span><span className={invalid?'danger-text':''}><b>{invalid}</b> com pendência</span></div><div className="csv-preview-table" role="region" aria-label="Prévia da importação" tabIndex={0}><table><thead><tr><th>Linha</th><th>Produto</th><th>Categoria</th><th>Status</th></tr></thead><tbody>{rows.slice(0,40).map(row=><tr key={`${row.row}-${row.slug}`} className={row.ok?'':'has-error'}><td>{row.row}</td><td><strong>{row.name||'Sem nome'}</strong><small>{row.slug}</small></td><td>{row.category||'—'}</td><td>{row.ok?'Pronto para rascunho':row.errors.join(' • ')}</td></tr>)}</tbody></table></div>{rows.length>40&&<small className="muted">Mostrando as primeiras 40 linhas da prévia.</small>}<div className="inline-actions"><button type="button" className="btn" onClick={()=>{setRows([]);setValid(0);setInvalid(0)}}>Trocar/revalidar arquivo</button><button type="button" className="btn btn-primary" onClick={commit} disabled={loading||valid===0}>{loading?'Importando…':`Importar ${valid} rascunho(s)`}</button></div></>}</section></div>}</>;
}
