'use client';
import { useCallback,useEffect,useState } from 'react';
import { AlertTriangle,Check,ClipboardCopy,KeyRound,Laptop,RefreshCw,ShieldAlert,ShieldCheck,Smartphone,Trash2 } from 'lucide-react';
import { fetchJson } from '@/lib/client';

type RecoveryStatus={configured:boolean;total:number;remaining:number};
type Device={id:string;device_hash:string;device_label:string;user_agent:string;first_seen_at:string;last_seen_at:string;last_login_at:string;revoked_at:string|null};
type SecurityEvent={id:number;event_type:'new_device_login'|'recovery_code_login'|'recovery_codes_rotated'|'device_revoked'|'critical_reauth'|'critical_action'|'security_webhook_failed';severity:'info'|'warning'|'critical';device_hash:string;device_label:string;summary:string;created_at:string;acknowledged_at:string|null};
type Overview={store:'database'|'stateless';recovery:RecoveryStatus;devices:Device[];events:SecurityEvent[];unread_count:number;current_device_hash:string;webhook:{configured:boolean;valid:boolean;signed:boolean}};
function dateTime(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(date);}
function deviceIcon(label:string){return /iphone|ipad|android/i.test(label)?<Smartphone size={18}/>:<Laptop size={18}/>;}
function eventLabel(type:SecurityEvent['event_type']){return type==='new_device_login'?'Novo dispositivo':type==='recovery_code_login'?'Login por recuperação':type==='recovery_codes_rotated'?'Códigos renovados':type==='device_revoked'?'Dispositivo removido':type==='critical_reauth'?'Identidade confirmada':type==='critical_action'?'Ação crítica':'Falha no alerta externo';}

export default function SecurityCenter(){
  const [data,setData]=useState<Overview|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [totp,setTotp]=useState('');const [showRotate,setShowRotate]=useState(false);const [newCodes,setNewCodes]=useState<string[]>([]);const [copied,setCopied]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await fetchJson<Overview>('/api/admin/security'));}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a central de segurança.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function rotate(){if(totp.length!==6)return;setBusy('rotate');setError('');setMessage('');try{const result=await fetchJson<{ok:boolean;codes:string[];remaining:number}>('/api/admin/security',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'rotate_recovery_codes',code:totp})});setNewCodes(result.codes);setTotp('');setShowRotate(false);setMessage('Novos códigos gerados. Salve-os agora: eles não serão exibidos novamente depois que esta lista for fechada.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível gerar novos códigos.');}finally{setBusy('');}}
  async function copyCodes(){try{await navigator.clipboard.writeText(newCodes.join('\n'));setCopied(true);setTimeout(()=>setCopied(false),2200);}catch{setError('Não foi possível copiar automaticamente. Selecione os códigos manualmente.');}}
  async function acknowledge(){setBusy('ack');setError('');try{await fetchJson('/api/admin/security',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'acknowledge_events'})});await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível marcar os alertas como lidos.');}finally{setBusy('');}}
  async function revokeDevice(device:Device){if(!confirm(`Remover “${device.device_label}” dos dispositivos reconhecidos e encerrar todas as sessões vinculadas?`))return;setBusy(device.id);setError('');try{const result=await fetchJson<{ok:boolean;logged_out?:boolean}>('/api/admin/security',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({device_id:device.id})});if(result.logged_out){location.href='/admin/login?reason=expired';return;}setMessage('Dispositivo removido e sessões vinculadas encerradas.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível remover o dispositivo.');}finally{setBusy('');}}
  const activeDevices=data?.devices.filter(device=>!device.revoked_at)||[];
  return <section className="admin-panel security-center"><div className="panel-subtitle"><div><div className="eyebrow">Proteção da conta</div><h2>Recuperação & alertas</h2><p className="muted">Códigos reserva de uso único, dispositivos reconhecidos e histórico de eventos importantes do acesso administrativo.</p></div><button type="button" className="btn" onClick={()=>void load()} disabled={loading||Boolean(busy)}><RefreshCw size={16}/> Atualizar</button></div>
    {data?.store==='stateless'&&<div className="session-warning"><ShieldAlert size={20}/><div><strong>Central de segurança aguardando Neon</strong><p>Recuperação, reconhecimento persistente de dispositivo e alertas exigem DATABASE_URL. O deploy de produção já bloqueia acesso administrativo sem Neon.</p></div></div>}
    {data?.store==='database'&&<>
      <div className="security-grid">
        <article className={`security-stat ${data.recovery.remaining<=2?'warning':''}`}><KeyRound size={21}/><div><strong>{data.recovery.remaining}</strong><span>códigos de recuperação restantes</span><small>{data.recovery.configured?`${data.recovery.total} gerados no conjunto atual`:'Nenhum conjunto gerado ainda'}</small></div></article>
        <article className={`security-stat ${data.unread_count?'warning':''}`}><AlertTriangle size={21}/><div><strong>{data.unread_count}</strong><span>alerta(s) não lido(s)</span><small>{activeDevices.length} dispositivo(s) reconhecido(s)</small></div></article><article className={`security-stat ${data.webhook.configured&&!data.webhook.valid?'warning':''}`}><ShieldCheck size={21}/><div><strong>{data.webhook.configured?(data.webhook.valid?'Ativo':'Inválido'):'Opcional'}</strong><span>alerta externo por webhook</span><small>{data.webhook.configured?(data.webhook.signed?'Payload assinado por HMAC-SHA256':'Configure ADMIN_SECURITY_WEBHOOK_SECRET para assinar'):'Configure no ambiente se quiser receber alertas fora do painel'}</small></div></article>
      </div>
      <div className="security-block"><div className="security-block-head"><div><h3>Códigos de recuperação</h3><p>Use um deles caso perca acesso ao autenticador. Cada código funciona apenas uma vez.</p></div><button type="button" className="btn" onClick={()=>{setShowRotate(value=>!value);setNewCodes([]);setError('');}} disabled={Boolean(busy)}>{data.recovery.configured?'Gerar novo conjunto':'Gerar códigos'}</button></div>
        {showRotate&&<div className="security-confirm"><label htmlFor="security-totp">Confirme com o código TOTP atual</label><div className="security-confirm-row"><input id="security-totp" value={totp} onChange={e=>setTotp(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" maxLength={6} placeholder="000000"/><button type="button" className="btn btn-primary" disabled={totp.length!==6||busy==='rotate'} onClick={()=>void rotate()}>{busy==='rotate'?'Gerando…':'Confirmar e substituir'}</button></div><small>Gerar um novo conjunto invalida imediatamente todos os códigos de recuperação anteriores.</small></div>}
        {newCodes.length>0&&<div className="recovery-codes" role="status"><div className="recovery-codes-head"><div><ShieldCheck size={20}/><div><strong>Salve estes códigos agora</strong><span>Depois de fechar esta lista, o servidor mantém apenas os hashes.</span></div></div><button type="button" className="btn" onClick={()=>void copyCodes()}>{copied?<><Check size={15}/> Copiados</>:<><ClipboardCopy size={15}/> Copiar todos</>}</button></div><div className="recovery-code-grid">{newCodes.map(code=><code key={code}>{code}</code>)}</div><button type="button" className="btn" onClick={()=>setNewCodes([])}>Já salvei; ocultar códigos</button></div>}
      </div>
      <div className="security-block"><div className="security-block-head"><div><h3>Dispositivos reconhecidos</h3><p>O navegador recebe um identificador aleatório HttpOnly; no banco fica somente o hash.</p></div></div><div className="known-device-list">{activeDevices.map(device=>{const current=device.device_hash===data.current_device_hash;return <article className="known-device" key={device.id}><div className="session-device-icon">{deviceIcon(device.device_label)}</div><div><div><strong>{device.device_label||'Dispositivo'}</strong>{current&&<span className="status-pill active">Atual</span>}</div><small>Primeiro acesso: {dateTime(device.first_seen_at)} • último login: {dateTime(device.last_login_at)}</small><small>{device.user_agent.slice(0,140)}{device.user_agent.length>140?'…':''}</small></div><button type="button" className="btn danger" disabled={Boolean(busy)} onClick={()=>void revokeDevice(device)}><Trash2 size={15}/>{busy===device.id?'Removendo…':current?'Remover este dispositivo':'Remover'}</button></article>})}{activeDevices.length===0&&<div className="empty-state">Nenhum dispositivo reconhecido encontrado.</div>}</div></div>
      <div className="security-block"><div className="security-block-head"><div><h3>Alertas de segurança</h3><p>Novos dispositivos, recuperação da conta e mudanças relevantes ficam registrados aqui.</p></div>{data.unread_count>0&&<button type="button" className="btn" disabled={busy==='ack'} onClick={()=>void acknowledge()}><Check size={15}/> {busy==='ack'?'Marcando…':'Marcar como lidos'}</button>}</div><div className="security-event-list">{data.events.map(event=><article className={`security-event ${event.severity} ${event.acknowledged_at?'read':'unread'}`} key={event.id}><span className="security-event-dot"/><div><div><strong>{eventLabel(event.event_type)}</strong>{!event.acknowledged_at&&<span className="status-pill active">Novo</span>}</div><p>{event.summary}</p><small>{dateTime(event.created_at)}{event.device_label?` • ${event.device_label}`:''}</small></div></article>)}{data.events.length===0&&<div className="empty-state">Nenhum evento de segurança registrado.</div>}</div></div>
    </>}
    {error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
  </section>;
}
