'use client';
import { useCallback,useEffect,useState } from 'react';
import { Laptop,RefreshCw,ShieldCheck,Smartphone,Trash2 } from 'lucide-react';
import { fetchJson } from '@/lib/client';

type Session={id:string;device_hash:string;device_label:string;user_agent:string;created_at:string;last_seen_at:string;expires_at:string;mfa_verified_at:string|null;last_reauth_at:string|null;auth_method:'password'|'totp'|'recovery';revoked_at:string|null};
type SessionsResponse={store:'database'|'stateless';current_session_id:string|null;sessions:Session[]};
function dateTime(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(date);}
function deviceIcon(label:string){return /iphone|ipad|android/i.test(label)?<Smartphone size={19}/>:<Laptop size={19}/>;}
export default function SessionManager(){
  const [data,setData]=useState<SessionsResponse|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await fetchJson<SessionsResponse>('/api/admin/sessions'));}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar as sessões.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function revoke(sessionId:string){if(!confirm('Encerrar esta sessão administrativa? O dispositivo precisará entrar novamente.'))return;setBusy(sessionId);setError('');setMessage('');try{const result=await fetchJson<{ok:boolean;logged_out?:boolean}>('/api/admin/sessions',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:sessionId})});if(result.logged_out){location.href='/admin/login';return;}setMessage('Sessão encerrada.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível encerrar a sessão.');}finally{setBusy('');}}
  async function revokeOthers(){if(!confirm('Encerrar todas as outras sessões administrativas?'))return;setBusy('others');setError('');setMessage('');try{const result=await fetchJson<{ok:boolean;revoked:number}>('/api/admin/sessions',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({action:'revoke_others'})});setMessage(`${result.revoked} outra(s) sessão(ões) encerrada(s).`);await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível encerrar as outras sessões.');}finally{setBusy('');}}
  return <section className="admin-panel session-manager"><div className="panel-subtitle"><div><div className="eyebrow">Segurança administrativa</div><h2>Sessões & dispositivos</h2><p className="muted">Veja onde o painel está conectado e encerre acessos que você não reconhece ou não usa mais.</p></div><button type="button" className="btn" onClick={()=>void load()} disabled={loading||Boolean(busy)}><RefreshCw size={16}/> Atualizar</button></div>
    {loading&&!data&&<div className="empty-state">Carregando sessões…</div>}
    {data?.store==='stateless'&&<div className="session-warning"><ShieldCheck size={20}/><div><strong>Controle revogável aguardando Neon</strong><p>Sem DATABASE_URL, a sessão continua assinada e protegida, mas a lista de dispositivos e a revogação remota ficam desativadas. Em produção, o preflight exige Neon.</p></div></div>}
    {data?.store==='database'&&<><div className="session-summary"><div><ShieldCheck size={20}/><span><strong>{data.sessions.length}</strong> sessão(ões) ativa(s)</span></div><button type="button" className="btn danger" disabled={busy==='others'||data.sessions.filter(s=>s.id!==data.current_session_id).length===0} onClick={revokeOthers}><Trash2 size={16}/> {busy==='others'?'Encerrando…':'Encerrar outras sessões'}</button></div><div className="session-list">{data.sessions.map(session=>{const current=session.id===data.current_session_id;return <article className={`session-card ${current?'current':''}`} key={session.id}><div className="session-device-icon">{deviceIcon(session.device_label)}</div><div className="session-info"><div><strong>{session.device_label||'Dispositivo'}</strong>{current&&<span className="status-pill active">Sessão atual</span>}</div><small>Última atividade: {dateTime(session.last_seen_at)}</small><small>Entrada: {dateTime(session.created_at)} • expira {dateTime(session.expires_at)}</small><small>{session.mfa_verified_at?`${session.auth_method==='recovery'?'Recuperação':'2FA'} verificado em ${dateTime(session.mfa_verified_at)}`:'Sessão sem 2FA (somente ambiente não produtivo)'}</small>{session.last_reauth_at&&<small>Confirmação reforçada: {dateTime(session.last_reauth_at)}</small>}{session.user_agent&&<code title={session.user_agent}>{session.user_agent.slice(0,120)}{session.user_agent.length>120?'…':''}</code>}</div><button type="button" className="btn danger" disabled={Boolean(busy)} onClick={()=>void revoke(session.id)}>{busy===session.id?'Encerrando…':current?'Encerrar esta':'Encerrar'}</button></article>})}{data.sessions.length===0&&<div className="empty-state">Nenhuma sessão ativa encontrada.</div>}</div></>}
    {error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
  </section>;
}
