import crypto from 'node:crypto';import fs from 'node:fs';import fsp from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {S3Client,ListObjectsV2Command,GetObjectCommand,HeadObjectCommand} from '@aws-sdk/client-s3';import {neon} from '@neondatabase/serverless';
import {assertIsolatedDrillDatabase} from '../lib/recovery-drill.ts';import {databaseBackupRoot,isCurrentDatabaseBackupObjectKey,isLegacyDatabaseBackupObjectKey,normalizeOffsitePrefix,selectLatestDatabaseBackupObject} from '../lib/offsite-backup.ts';
import {normalizeExternalDrEndpoint,normalizeStorageBucket} from '../lib/dr-storage-policy.ts';import {decryptBackupText} from '../lib/backup-encryption.ts';import {verifyBackupText} from '../lib/backup-restore.ts';
function required(name){const v=String(process.env[name]||'').trim();if(!v)throw new Error(`${name} ausente`);return v;}
function run(label,args,env){const r=spawnSync(process.execPath,args,{cwd:process.cwd(),env:{...process.env,...env},encoding:'utf8',maxBuffer:4*1024*1024});process.stdout.write(r.stdout||'');process.stderr.write(r.stderr||'');if(r.status!==0)throw new Error(`${label} falhou`);}
async function writeBody(body,file){if(!body)throw new Error('Backup remoto sem corpo');const out=fs.createWriteStream(file),hash=crypto.createHash('sha256');let bytes=0;for await(const chunk of body){const b=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);hash.update(b);bytes+=b.length;if(bytes>40*1024*1024)throw new Error('Backup remoto excede o limite seguro de 40 MB');if(!out.write(b))await new Promise(r=>out.once('drain',r));}await new Promise((resolve,reject)=>out.end(e=>e?reject(e):resolve()));return{sha256:hash.digest('hex'),bytes};}
async function listObjects(client,bucket,prefix){let token;const items=[];do{const page=await client.send(new ListObjectsV2Command({Bucket:bucket,Prefix:prefix,ContinuationToken:token}));items.push(...(page.Contents||[]));token=page.IsTruncated?page.NextContinuationToken:undefined;}while(token);return items;}
const prod=required('DATABASE_URL'),drill=required('DRILL_DATABASE_URL');if(String(process.env.RECOVERY_DRILL_CONFIRM_ISOLATED||'')!=='1')throw new Error('RECOVERY_DRILL_CONFIRM_ISOLATED=1 é obrigatório');assertIsolatedDrillDatabase(prod,drill);
const endpoint=normalizeExternalDrEndpoint(required('BACKUP_S3_ENDPOINT'),'BACKUP_S3_ENDPOINT'),bucket=normalizeStorageBucket(required('BACKUP_S3_BUCKET'),'BACKUP_S3_BUCKET'),accessKeyId=required('BACKUP_S3_ACCESS_KEY_ID'),secretAccessKey=required('BACKUP_S3_SECRET_ACCESS_KEY'),region=String(process.env.BACKUP_S3_REGION||'auto'),prefix=normalizeOffsitePrefix(process.env.BACKUP_S3_PREFIX);const client=new S3Client({endpoint,region,forcePathStyle:String(process.env.BACKUP_S3_FORCE_PATH_STYLE||'1')!=='0',credentials:{accessKeyId,secretAccessKey}});
let candidates=await listObjects(client,bucket,`${databaseBackupRoot(prefix)}/`);let latest=selectLatestDatabaseBackupObject(candidates,prefix),legacy=false;if(!latest){candidates=(await listObjects(client,bucket,`${prefix}/`)).filter(item=>item.Key&&isLegacyDatabaseBackupObjectKey(item.Key,prefix));latest=selectLatestDatabaseBackupObject(candidates,prefix);legacy=true;}if(!latest?.Key)throw new Error('Nenhum backup de banco offsite válido encontrado');if(!isCurrentDatabaseBackupObjectKey(latest.Key,prefix)&&!isLegacyDatabaseBackupObjectKey(latest.Key,prefix))throw new Error('Objeto selecionado não pertence ao namespace de backup do banco');
const tmp=await fsp.mkdtemp(path.join(os.tmpdir(),'marques-recovery-drill-')),started=Date.now();try{const file=path.join(tmp,'latest.encrypted.json'),head=await client.send(new HeadObjectCommand({Bucket:bucket,Key:latest.Key})),obj=await client.send(new GetObjectCommand({Bucket:bucket,Key:latest.Key})),downloaded=await writeBody(obj.Body,file);const metadataSha=String(head.Metadata?.['envelope-sha256']||'').toLowerCase();if(metadataSha&&metadataSha!==downloaded.sha256)throw new Error('SHA-256 do envelope diverge do metadado remoto');if(!legacy&&!/^[0-9a-f]{64}$/.test(metadataSha))throw new Error('Backup no namespace database/ sem envelope-sha256 verificável');
const encrypted=await fsp.readFile(file,'utf8'),decrypted=decryptBackupText(encrypted,{requireEncryption:true}),verified=verifyBackupText(decrypted.plaintext,{requireAuthenticity:true});if(!legacy){const contract=String(head.Metadata?.['backup-contract']||''),schema=String(head.Metadata?.['schema-version']||''),contentSha=String(head.Metadata?.['content-sha256']||'').toLowerCase();if(contract!==String(verified.backup.backup_format||'')||schema!==String(verified.schemaVersion)||contentSha!==verified.sha256)throw new Error('Metadados remotos não atestam o conteúdo do backup selecionado');}
run('Verificação strict',['--no-warnings','--experimental-strip-types','scripts/verify-backup.mjs',file,'--strict'],process.env);run('Setup do banco de drill',['scripts/setup-db.mjs'],{DATABASE_URL:drill});run('Restore real no banco de drill',['--no-warnings','--experimental-strip-types','scripts/restore-db.mjs',file,'--apply','--confirm=RESTAURAR'],{DATABASE_URL:drill});run('db:verify do banco de drill',['scripts/verify-db.mjs'],{DATABASE_URL:drill});const duration=Date.now()-started,target=crypto.createHash('sha256').update(new URL(drill).hostname).digest('hex').slice(0,32),sql=neon(prod);await sql.query('INSERT INTO recovery_drill_receipts(backup_object_key,backup_sha256,drill_target_fingerprint,duration_ms,succeeded_at) VALUES($1,$2,$3,$4,now())',[latest.Key,downloaded.sha256,target,duration]);console.log(`RECOVERY_DRILL_OK key=${latest.Key} sha256=${downloaded.sha256} contract=${String(verified.backup.backup_format||'')} schema=${verified.schemaVersion} legacy_namespace=${legacy?1:0} duration_ms=${duration}`);}finally{await fsp.rm(tmp,{recursive:true,force:true});}
