import { neon } from '@neondatabase/serverless';
import fs from 'node:fs';
import { backupErrorMessage,verifyBackupText } from '../lib/backup-restore.ts';
import { mergePrivacyTombstones,sanitizeRestorePayloadPrivacy } from '../lib/privacy.ts';
import { decryptBackupText } from '../lib/backup-encryption.ts';
import { assertNoMediaTombstoneReferences,mergeMediaDeletionTombstones } from '../lib/media-tombstones.ts';

const file=process.argv.find(arg=>!arg.startsWith('--')&&arg!==process.argv[0]&&arg!==process.argv[1]);const apply=process.argv.includes('--apply');const confirm=process.argv.includes('--confirm=RESTAURAR');
if(!file){console.error('Uso: npm run db:restore -- backup.encrypted.json [--apply --confirm=RESTAURAR]');process.exit(2);}if(!process.env.DATABASE_URL){console.error('Defina DATABASE_URL.');process.exit(2);}const sql=neon(process.env.DATABASE_URL);
let verified;let encryption;try{const decrypted=decryptBackupText(fs.readFileSync(file,'utf8'),{requireEncryption:apply});encryption=decrypted.encryption;verified=verifyBackupText(decrypted.plaintext,{requireAuthenticity:apply});}catch(error){console.error(backupErrorMessage(error));process.exit(1);}
const [schema]=await sql`SELECT EXISTS(SELECT 1 FROM pg_proc WHERE proname='marques_restore_business_payload' AND pronargs=5) AS restore_ready, EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name='admin_restore_snapshots') AS snapshots_ready, EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name='privacy_requests') AS privacy_ready, EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name='media_deletion_tombstones') AS media_ready, EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name='media_lifecycle_leases') AS lease_ready, EXISTS(SELECT 1 FROM pg_proc WHERE proname='marques_cancel_media_lease' AND pronargs=4) AS lease_cancel_ready`;
if(!schema?.restore_ready||!schema?.snapshots_ready||!schema?.privacy_ready||!schema?.media_ready||!schema?.lease_ready||!schema?.lease_cancel_ready){console.error('Schema de restauração V6.50/schema 27 ausente. Execute npm run db:setup e npm run db:verify antes.');process.exit(1);}
const [currentRow]=await sql`SELECT marques_current_business_restore_counts() AS counts`;const current=currentRow?.counts||{};const tombstoneRows=await sql`SELECT subject_hash,identity_type,action,matched_inquiries,created_at,last_applied_at FROM privacy_requests WHERE action='anonymized'`;const merged=mergePrivacyTombstones(tombstoneRows,verified.privacyTombstones);const tombstoneHashes=new Set(merged.map(row=>row.subject_hash));const sanitized=sanitizeRestorePayloadPrivacy(verified.restorePayload,tombstoneHashes);const currentMedia=await sql`SELECT url,storage_key,deleted_at FROM media_deletion_tombstones ORDER BY storage_key,url`;const effectiveMedia=mergeMediaDeletionTombstones(currentMedia,verified.mediaTombstones);assertNoMediaTombstoneReferences(sanitized.payload,effectiveMedia);const restorePayload=verified.mediaRecovery.status==='embedded'?{...sanitized.payload,media_deletion_tombstones:effectiveMedia}:sanitized.payload;const effectiveCounts={...verified.counts,inquiry_activity:Array.isArray(sanitized.payload.inquiry_activity)?sanitized.payload.inquiry_activity.length:Number(verified.counts.inquiry_activity||0)};
console.log(`Backup: ${file}`);console.log(`Criptografia: ${encryption.status}${encryption.key_source?` (${encryption.key_source})`:''}`);console.log(`SHA-256: ${verified.sha256}`);console.log(`Schema do backup: ${verified.schemaVersion}`);console.log(`Autenticidade: ${verified.authenticity.status}${verified.authenticity.key_source?` (${verified.authenticity.key_source})`:''}`);console.log(`Disaster recovery de privacidade: ${verified.privacyRecovery.status} (${verified.privacyTombstones.length} tombstone(s) embutida(s), ${merged.length} após merge)`);console.log(`Disaster recovery de mídia: ${verified.mediaRecovery.status} (${verified.mediaTombstones.length} tombstone(s) embutida(s), ${effectiveMedia.length} efetiva(s) após proteção monotônica)`);if(sanitized.anonymizedCount)console.log(`Privacidade: ${sanitized.anonymizedCount} atendimento(s) permanecerão anonimizados; ${sanitized.removedActivityCount} evento(s) de timeline serão descartados.`);console.log('');
for(const key of Object.keys(effectiveCounts)){console.log(`${key}: atual=${Number(current[key]||0)} -> backup=${Number(effectiveCounts[key]||0)}`);}if(!apply){console.log('\nDRY-RUN concluído. Nenhum dado foi alterado. Para aplicar: --apply --confirm=RESTAURAR');process.exit(0);}if(!confirm){console.error('Aplicação bloqueada: informe também --confirm=RESTAURAR.');process.exit(2);}
const [row]=await sql`SELECT marques_restore_business_payload(${JSON.stringify(restorePayload)}::jsonb,${JSON.stringify(effectiveCounts)}::jsonb,${verified.sha256},${JSON.stringify(merged)}::jsonb,${'merge'}) AS result`;console.log('Restauração concluída.',JSON.stringify(row?.result||{}));
