import { readFileSync } from 'node:fs';
import { neon } from '@neondatabase/serverless';
if(!process.env.DATABASE_URL){console.error('Defina DATABASE_URL antes de executar npm run db:seed');process.exit(1);}
const sql=neon(process.env.DATABASE_URL);
const catalog=JSON.parse(readFileSync(new URL('../data/starter-catalog.json',import.meta.url),'utf8'));

// Compatibilidade não destrutiva com os slugs históricos.
await sql`UPDATE categories SET slug='caixas-personalizadas',name='Caixas personalizadas',updated_at=now() WHERE slug='caixinhas-milk' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug='caixas-personalizadas')`;
await sql`UPDATE categories SET slug='flores-acabamentos',name='Flores & acabamentos',updated_at=now() WHERE slug='flores' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug='flores-acabamentos')`;
await sql`UPDATE categories SET slug='mesa-festa',name='Mesa & festa',updated_at=now() WHERE slug='outros' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug='mesa-festa')`;

for(const category of catalog.categories){
  await sql`INSERT INTO categories (slug,name,description,image_url,active,sort_order)
    VALUES (${category.slug},${category.name},${category.description},${category.image_url},true,${category.sort_order})
    ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,image_url=EXCLUDED.image_url,active=true,sort_order=EXCLUDED.sort_order,updated_at=now()`;
}
for(let i=0;i<catalog.products.length;i++){
  const item=catalog.products[i];
  const customization=JSON.stringify(item.customization_fields||[]);
  await sql`INSERT INTO products (slug,name,category,category_id,description,price_cents,image_urls,featured,active,stock_status,tags,sort_order,min_quantity,production_time,badge,customization_fields,publish_at,unpublish_at)
    VALUES (${item.slug},${item.name},${item.category},(SELECT id FROM categories WHERE name=${item.category} LIMIT 1),${item.description},${item.price_cents},${[item.image_url]},${Boolean(item.featured)},true,${item.stock_status},${item.tags},${i+1},${item.min_quantity},${item.production_time},${item.badge||''},${customization}::jsonb,NULL,NULL)
    ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,category_id=EXCLUDED.category_id,description=EXCLUDED.description,price_cents=EXCLUDED.price_cents,image_urls=CASE WHEN cardinality(products.image_urls)=0 OR products.image_urls <@ ARRAY['/placeholder-topo.svg','/placeholder-milk.svg','/placeholder-kit.svg']::text[] THEN EXCLUDED.image_urls ELSE products.image_urls END,featured=EXCLUDED.featured,active=true,stock_status=EXCLUDED.stock_status,tags=EXCLUDED.tags,sort_order=EXCLUDED.sort_order,min_quantity=EXCLUDED.min_quantity,production_time=EXCLUDED.production_time,badge=EXCLUDED.badge,customization_fields=EXCLUDED.customization_fields,updated_at=now()`;
}
const brand=process.env.NEXT_PUBLIC_SITE_NAME||'Merlin Encantos em Papel';
const whatsapp=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||'';const instagram=process.env.NEXT_PUBLIC_INSTAGRAM_URL||'';const location=process.env.NEXT_PUBLIC_LOCATION||'Santa Inês - MA';const email=process.env.NEXT_PUBLIC_CONTACT_EMAIL||'';
await sql`INSERT INTO site_settings (id,brand_name,brand_initial,logo_url,hero_eyebrow,hero_title,hero_highlight,hero_description,whatsapp_number,instagram_url,location,contact_email,about_title,about_text,seo_title,seo_description)
  VALUES (1,${brand},'M','/merlin-logo.webp','Merlin • Encantos em Papel • Feita sob encomenda','Sua ideia vira uma festa com identidade.','identidade','Topos, caixas, kits, lembrancinhas e detalhes personalizados para transformar referências, temas e histórias em uma comemoração única.',${whatsapp},${instagram},${location},${email},'Papelaria criada para combinar com a sua história.','Cada pedido começa por uma ideia e ganha forma com composição, corte, camadas e acabamento pensados para a sua comemoração.',${`${brand} | Papelaria Personalizada`},'Catálogo de inspirações, topos de bolo, caixas, kits, lembrancinhas e papelaria personalizada da Merlin Encantos em Papel.')
  ON CONFLICT (id) DO UPDATE SET brand_name=CASE WHEN site_settings.brand_name IN ('Marques Papelaria','K&F Papelaria Criativa','K&F Papelaria') THEN EXCLUDED.brand_name ELSE site_settings.brand_name END,brand_initial='M',logo_url=CASE WHEN site_settings.logo_url='' OR site_settings.logo_url LIKE '%kf-%' THEN EXCLUDED.logo_url ELSE site_settings.logo_url END,hero_eyebrow=CASE WHEN site_settings.brand_name IN ('Marques Papelaria','K&F Papelaria Criativa','K&F Papelaria') THEN EXCLUDED.hero_eyebrow ELSE site_settings.hero_eyebrow END,hero_title=CASE WHEN site_settings.brand_name IN ('Marques Papelaria','K&F Papelaria Criativa','K&F Papelaria') THEN EXCLUDED.hero_title ELSE site_settings.hero_title END,hero_highlight=CASE WHEN site_settings.brand_name IN ('Marques Papelaria','K&F Papelaria Criativa','K&F Papelaria') THEN EXCLUDED.hero_highlight ELSE site_settings.hero_highlight END,hero_description=CASE WHEN site_settings.brand_name IN ('Marques Papelaria','K&F Papelaria Criativa','K&F Papelaria') THEN EXCLUDED.hero_description ELSE site_settings.hero_description END,whatsapp_number=CASE WHEN site_settings.whatsapp_number='' THEN EXCLUDED.whatsapp_number ELSE site_settings.whatsapp_number END,instagram_url=CASE WHEN site_settings.instagram_url='' THEN EXCLUDED.instagram_url ELSE site_settings.instagram_url END,location=CASE WHEN site_settings.location='' THEN EXCLUDED.location ELSE site_settings.location END,contact_email=CASE WHEN site_settings.contact_email='' THEN EXCLUDED.contact_email ELSE site_settings.contact_email END,about_title=CASE WHEN site_settings.brand_name IN ('Marques Papelaria','K&F Papelaria Criativa','K&F Papelaria') THEN EXCLUDED.about_title ELSE site_settings.about_title END,about_text=CASE WHEN site_settings.brand_name IN ('Marques Papelaria','K&F Papelaria Criativa','K&F Papelaria') THEN EXCLUDED.about_text ELSE site_settings.about_text END,seo_title=CASE WHEN site_settings.seo_title LIKE 'Marques%' OR site_settings.seo_title LIKE 'K&F%' THEN EXCLUDED.seo_title ELSE site_settings.seo_title END,seo_description=CASE WHEN site_settings.seo_description LIKE '%Marques%' OR site_settings.seo_description='' THEN EXCLUDED.seo_description ELSE site_settings.seo_description END,updated_at=now()`;
console.log(`Seed Merlin V6.62 concluído: ${catalog.categories.length} categorias e ${catalog.products.length} produtos com preços iniciais.`);
