import { hasRecentAdminReauthentication,isAdmin } from '@/lib/auth';
import { categoryExists, deleteProduct,permanentlyDeleteProduct, logAdminAction, StaleWriteError, updateProduct, requireCriticalAuditIntent } from '@/lib/db';
import { productSchema } from '@/lib/validation';
import { isUuid, readJsonBody, sameOriginRequest } from '@/lib/security';
import { serverFailure } from '@/lib/observability';
import { productPublishIssues, publishIssuesMessage } from '@/lib/product-readiness';
import { recordAdminSecurityEventWithAlert } from '@/lib/admin-security-alerts';
import { expectedUpdatedAtFromRequest,requireExpectedUpdatedAt } from '@/lib/concurrency';

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){
  if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401});if(!sameOriginRequest(request))return Response.json({error:'Origem inválida.'},{status:403});
  const {id}=await params;if(!isUuid(id))return Response.json({error:'ID inválido.'},{status:400});
  try{const body=await readJsonBody(request,64_000);const expectedUpdatedAt=requireExpectedUpdatedAt(body.expected_updated_at);const parsed=productSchema.safeParse(body);if(!parsed.success)return Response.json({error:'Dados inválidos. Confira os campos do produto.',details:parsed.error.flatten()},{status:400});if(!(await categoryExists(parsed.data.category)))return Response.json({error:'Selecione uma categoria ativa e cadastrada.'},{status:400});const publishIssues=parsed.data.active?productPublishIssues(parsed.data):[];if(publishIssues.length)return Response.json({error:publishIssuesMessage(publishIssues),issues:publishIssues},{status:422});const product=await updateProduct(id,parsed.data,expectedUpdatedAt);if(!product)return Response.json({error:'Produto não encontrado.'},{status:404});await logAdminAction('update','product',id,`Produto atualizado: ${product.name}`);return Response.json({product});}
  catch(e){if(e instanceof StaleWriteError)return Response.json({error:e.message},{status:409});const msg=(e instanceof Error?e.message:'').toLowerCase();if(msg.includes('unique')||msg.includes('duplicate'))return Response.json({error:'Já existe outro produto com esse slug.'},{status:409});if((e instanceof Error?e.message:'')==='PAYLOAD_TOO_LARGE')return Response.json({error:'Os dados do produto excedem o limite permitido.'},{status:413});return await serverFailure('admin.products.update',e);}
}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401});if(!sameOriginRequest(request))return Response.json({error:'Origem inválida.'},{status:403});const{id}=await params;if(!isUuid(id))return Response.json({error:'ID inválido.'},{status:400});try{const expectedUpdatedAt=expectedUpdatedAtFromRequest(request);const permanent=new URL(request.url).searchParams.get('permanent')==='1';if(permanent){if(!(await hasRecentAdminReauthentication()))return Response.json({error:'Confirme novamente sua identidade para excluir definitivamente.',reauth_required:true},{status:428});await requireCriticalAuditIntent('delete_product_permanent','product',id,'Exclusão definitiva de produto autorizada após step-up MFA.');const deleted=await permanentlyDeleteProduct(id,expectedUpdatedAt);if(!deleted)return Response.json({error:'Produto arquivado não encontrado.'},{status:404});await logAdminAction('delete_permanent','product',id,'Produto excluído definitivamente da lixeira.');await recordAdminSecurityEventWithAlert({eventType:'critical_action',severity:'warning',summary:`Produto excluído definitivamente da lixeira (${id}).`});return Response.json({ok:true,permanent:true});}const product=await deleteProduct(id,expectedUpdatedAt);if(!product)return Response.json({error:'Produto não encontrado.'},{status:404});await logAdminAction('archive','product',id,`Produto arquivado: ${product.name}`);return Response.json({ok:true,archived:true,product});}catch(e){if(e instanceof StaleWriteError)return Response.json({error:e.message},{status:409});return await serverFailure('admin.products.delete',e);}}
