import { isAdmin } from '@/lib/auth';
import { deleteSocialContentPlan, logAdminAction, StaleWriteError, updateSocialContentPlan } from '@/lib/db';
import { serverFailure } from '@/lib/observability';
import { readJsonBody, sameOriginRequest } from '@/lib/security';
import { socialContentPlanSchema } from '@/lib/validation';
import { expectedUpdatedAtFromRequest,requireExpectedUpdatedAt } from '@/lib/concurrency';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401});if(!sameOriginRequest(request))return Response.json({error:'Origem inválida.'},{status:403});const{id}=await params;if(!UUID.test(id))return Response.json({error:'ID inválido.'},{status:400});try{const body=await readJsonBody(request,16000);const expectedUpdatedAt=requireExpectedUpdatedAt(body.expected_updated_at);const parsed=socialContentPlanSchema.safeParse(body);if(!parsed.success)return Response.json({error:'Confira os dados do planejamento.',details:parsed.error.flatten()},{status:400});const plan=await updateSocialContentPlan(id,parsed.data,expectedUpdatedAt);if(!plan)return Response.json({error:'Planejamento não encontrado.'},{status:404});await logAdminAction('update','social_plan',id,`Planejamento atualizado: ${plan.title}`);return Response.json({plan});}catch(e){if(e instanceof StaleWriteError)return Response.json({error:e.message},{status:409});return await serverFailure('admin.social-plan.update',e);}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401});if(!sameOriginRequest(request))return Response.json({error:'Origem inválida.'},{status:403});const{id}=await params;if(!UUID.test(id))return Response.json({error:'ID inválido.'},{status:400});try{const expectedUpdatedAt=expectedUpdatedAtFromRequest(request);const deleted=await deleteSocialContentPlan(id,expectedUpdatedAt);if(!deleted)return Response.json({error:'Planejamento não encontrado.'},{status:404});await logAdminAction('delete','social_plan',id,'Planejamento de conteúdo excluído.');return Response.json({ok:true});}catch(e){if(e instanceof StaleWriteError)return Response.json({error:e.message},{status:409});return await serverFailure('admin.social-plan.delete',e);}}
