import crypto from 'node:crypto';
import { hasRecentAdminReauthentication,isAdmin } from '@/lib/auth';
import { applyBusinessRestorePayload,checkDataIntegrity,checkSchema,getBusinessRestoreCounts,listBusinessRestoreSnapshots,logAdminAction,prepareBusinessRestorePayloadForSafety,restoreBusinessSnapshot, requireCriticalAuditIntent } from '@/lib/db';
import { backupErrorMessage,verifyBackupText } from '@/lib/backup-restore';
import { decryptBackupText } from '@/lib/backup-encryption';
import { protectedRateLimit,isUuid,sameOriginRequest } from '@/lib/security';
import { readTextBodyWithinLimit } from '@/lib/request-limits';
import { recordAdminSecurityEventWithAlert } from '@/lib/admin-security-alerts';
import { serverFailure } from '@/lib/observability';
import { EXPECTED_SCHEMA_VERSION } from '@/lib/release';

export const dynamic='force-dynamic';
const MAX_BYTES=36*1024*1024;
function cacheHeaders(){return{'cache-control':'private, no-store'};}
async function backupText(request:Request){try{return await readTextBodyWithinLimit(request,MAX_BYTES);}catch(error){if(error instanceof Error&&error.message==='PAYLOAD_TOO_LARGE')throw new Error('BACKUP_TOO_LARGE');throw error;}}
function planSections(current:Record<string,number>,backup:Record<string,number>){const labels:Record<string,string>={products:'Produtos',archived_products:'Produtos arquivados',categories:'Categorias',inquiries:'Orçamentos/CRM',settings:'Configurações do site',testimonials:'Avaliações',faqs:'FAQ',inquiry_activity:'Histórico dos orçamentos',social_content_plans:'Planejamento de conteúdo',marketing_campaigns:'Campanhas',site_events_daily:'Analytics agregados'};return Object.keys(backup).map(key=>({key,label:labels[key]||key,current:Number(current[key]||0),backup:Number(backup[key]||0),delta:Number(backup[key]||0)-Number(current[key]||0)}));}

export async function GET(){if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401,headers:cacheHeaders()});try{return Response.json({snapshots:await listBusinessRestoreSnapshots(10)},{headers:cacheHeaders()});}catch(error){return await serverFailure('admin.restore.snapshots',error);}}

export async function POST(request:Request){
  if(!(await isAdmin()))return Response.json({error:'Não autorizado.'},{status:401,headers:cacheHeaders()});
  if(!sameOriginRequest(request))return Response.json({error:'Origem inválida.'},{status:403,headers:cacheHeaders()});
  const url=new URL(request.url);const action=url.searchParams.get('action')||'plan';
  try{
    if(action==='rollback'){
      if(!(await hasRecentAdminReauthentication()))return Response.json({error:'Confirme novamente sua identidade para reverter uma restauração.',reauth_required:true},{status:428,headers:cacheHeaders()});
      const rate=await protectedRateLimit(request,'admin-restore-rollback',4,15*60_000);if(!rate.allowed)return Response.json({error:'Muitas tentativas de recuperação. Aguarde alguns minutos.'},{status:429,headers:cacheHeaders()});
      const snapshotId=url.searchParams.get('snapshot_id')||'';const confirmation=url.searchParams.get('confirmation')||'';if(!isUuid(snapshotId)||confirmation!=='REVERTER')return Response.json({error:'Confirmação de reversão inválida.'},{status:400,headers:cacheHeaders()});
      await requireCriticalAuditIntent('rollback_restore','system',snapshotId,'Rollback de snapshot autorizado após step-up MFA.');const result=await restoreBusinessSnapshot(snapshotId);const integrity=await checkDataIntegrity();if(!integrity.ok){await restoreBusinessSnapshot(result.snapshot.id);return Response.json({error:'A reversão produziria dados inconsistentes e foi desfeita automaticamente.',issues:integrity.issues},{status:422,headers:cacheHeaders()});}
      await logAdminAction('rollback_restore','system',snapshotId,'Snapshot de pré-restauração reaplicado com sucesso.',{severity:'critical',metadata:{safety_snapshot_id:result.snapshot.id,counts:result.counts}});await recordAdminSecurityEventWithAlert({eventType:'critical_action',severity:'critical',summary:'Rollback de dados administrativos executado após step-up MFA.'});
      return Response.json({ok:true,counts:result.counts,safety_snapshot_id:result.snapshot.id},{headers:cacheHeaders()});
    }
    const raw=await backupText(request);let verified;let encryption;try{const decrypted=decryptBackupText(raw,{requireEncryption:process.env.NODE_ENV==='production'});encryption=decrypted.encryption;verified=verifyBackupText(decrypted.plaintext,{requireAuthenticity:process.env.NODE_ENV==='production'});}catch(error){return Response.json({error:backupErrorMessage(error)},{status:400,headers:cacheHeaders()});}
    const targetSchema=await checkSchema();if(!targetSchema.configured||targetSchema.version<EXPECTED_SCHEMA_VERSION)return Response.json({error:`O banco precisa estar no schema ${EXPECTED_SCHEMA_VERSION} antes de planejar/aplicar restaurações nesta versão.`},{status:409,headers:cacheHeaders()});const prepared=await prepareBusinessRestorePayloadForSafety(verified.restorePayload,verified.counts,verified.privacyTombstones);const current=await getBusinessRestoreCounts();const sections=planSections(current,prepared.counts);const effectivePlanHash=crypto.createHash('sha256').update(JSON.stringify({base:verified.planHash,counts:prepared.counts,privacy_anonymized:prepared.anonymizedCount,privacy_activity_removed:prepared.removedActivityCount,privacy_tombstones:prepared.tombstones.map(row=>`${row.identity_type}:${row.subject_hash}`),media_tombstones:prepared.mediaTombstones.map(row=>`${row.storage_key}:${row.deleted_at}`),media_mode:prepared.mediaMode})).digest('hex');const privacyWarnings=[...verified.warnings];if(prepared.anonymizedCount)privacyWarnings.unshift(`${prepared.anonymizedCount} atendimento(s) do backup serão mantidos anonimizados por solicitações de privacidade já registradas.`);if(prepared.removedActivityCount)privacyWarnings.unshift(`${prepared.removedActivityCount} evento(s) de timeline ligados a identidades apagadas não serão restaurados.`);
    if(action==='plan')return Response.json({plan_hash:effectivePlanHash,backup:{sha256:verified.sha256,created_at:verified.createdAt,schema_version:verified.schemaVersion,version:Number(verified.backup.version||0),format:String(verified.backup.backup_format||''),authenticity:verified.authenticity,encryption},current_counts:current,backup_counts:prepared.counts,sections,warnings:privacyWarnings,audit_rows:Array.isArray(verified.content.audit)?verified.content.audit.length:0,privacy:{anonymized:prepared.anonymizedCount,activity_removed:prepared.removedActivityCount,tombstones:prepared.tombstoneCount,embedded_tombstones:verified.privacyTombstones.length,disaster_recovery:verified.privacyRecovery.status},media:{embedded_tombstones:verified.mediaTombstones.length,effective_tombstones:prepared.mediaTombstones.length,mode:prepared.mediaMode,disaster_recovery:verified.mediaRecovery.status}},{headers:cacheHeaders()});
    if(action!=='apply')return Response.json({error:'Ação inválida.'},{status:400,headers:cacheHeaders()});
    if(!(await hasRecentAdminReauthentication()))return Response.json({error:'Confirme novamente sua identidade antes de restaurar dados.',reauth_required:true},{status:428,headers:cacheHeaders()});
    const rate=await protectedRateLimit(request,'admin-restore-apply',3,30*60_000);if(!rate.allowed)return Response.json({error:'Limite de restaurações atingido. Aguarde antes de tentar novamente.'},{status:429,headers:cacheHeaders()});
    if(url.searchParams.get('confirmation')!=='RESTAURAR'||url.searchParams.get('plan_hash')!==effectivePlanHash)return Response.json({error:'O plano ou a confirmação da restauração não corresponde ao backup analisado.'},{status:409,headers:cacheHeaders()});
    try{
      await requireCriticalAuditIntent('restore','system',null,'Restauração de backup autorizada após step-up MFA.',{backup_sha256:verified.sha256.slice(0,16),backup_schema:verified.schemaVersion});
      const result=await applyBusinessRestorePayload(verified.restorePayload,verified.counts,verified.sha256,verified.privacyTombstones);const integrity=await checkDataIntegrity();
      if(!integrity.ok){await restoreBusinessSnapshot(result.snapshot.id);return Response.json({error:'A restauração gerou inconsistência e o estado anterior foi recuperado automaticamente.',issues:integrity.issues,safety_snapshot_id:result.snapshot.id},{status:422,headers:cacheHeaders()});}
      await logAdminAction('restore','system',null,`Backup ${verified.sha256.slice(0,12)}… restaurado com snapshot de segurança.`,{severity:'critical',metadata:{backup_sha256:verified.sha256,backup_schema:verified.schemaVersion,safety_snapshot_id:result.snapshot.id,counts:result.counts}});await recordAdminSecurityEventWithAlert({eventType:'critical_action',severity:'critical',summary:'Restauração administrativa de backup executada após step-up MFA.'});
      return Response.json({ok:true,counts:result.counts,media:result.media,safety_snapshot:result.snapshot},{headers:cacheHeaders()});
    }catch(error){await logAdminAction('restore_failed','system',null,'Restauração de backup falhou; a transação do banco foi revertida.',{severity:'critical',metadata:{backup_sha256:verified.sha256}});throw error;}
  }catch(error){const message=error instanceof Error?error.message:'';if(message==='BACKUP_TOO_LARGE')return Response.json({error:'O arquivo de backup criptografado excede 36 MB.'},{status:413,headers:cacheHeaders()});if(message==='BACKUP_MEDIA_REFERENCE_CONFLICT')return Response.json({error:'A restauração foi bloqueada porque o backup tenta referenciar uma mídia marcada como excluída no cofre de tombstones.'},{status:409,headers:cacheHeaders()});if(message.includes('MEDIA_LIFECYCLE_ACTIVE'))return Response.json({error:'Há uma operação de mídia em andamento. Conclua/reconcilie o lifecycle antes de restaurar o banco.'},{status:409,headers:{...cacheHeaders(),'retry-after':'30'}});return await serverFailure('admin.restore',error);}
}
